
################################################################  systemd
- systemd:    daemon_reload="yes"
- wait_for:    delay=3 timeout=0

- name:       reload  daemon
  block:
     - systemd:    name="grafana-server"   daemon_reload="yes"   enabled=no  state="stopped"  
       when:       ansible_facts.services["grafana-server.service"].state  == 'disabled'
  rescue:
     - wait_for:    delay=10 timeout=0
     - systemd:     name="grafana-server"   daemon_reload="yes"   enabled=no  state="stopped"  
       when:        ansible_facts.services["grafana-server.service"].state  == 'disabled'


-  systemd:    name="grafana-server"   daemon_reload="yes"   enabled=no  state="restarted"  
   when:  ansible_facts.services["grafana-server.service"].state  == 'running'


# firewall-cmd --add-port=3000/tcp --permanent

