groups:
- name: postgresql.rules
  rules:
  - alert: PostgreSQL_ReplicationLagTooLarge
expr: |
      (pg_replication_lag > 120)
        AND ON(instance)
      (pg_replication_is_replica == 1)
    annotations:
      description: |
        Replication lag on server {{$labels.instance}} is currently
        {{$value | humanizeDuration }}
      runbook: troubleshooting/postgres.md#replication-is-lagging-or-has-stopped
      title: 'Postgres Replication lag is over 2 minutes'
