   - name:     group vagrant
     group:    name=vagrant  gid=998     state=present
     when:     need_role_vagrant

   - name:     group vboxsf
     group:    name=vboxsf    gid=999     state=present

   - name:     group ioannis
     group:    name=ioannis   gid=1000
     when:     need_role_ioannis

   - name:     group postgres
     group:    name=postgres  gid=1001
     when:     need_role_postgres

   - name:     group nagios
     group:    name=nagios    gid=1002
     when:     need_role_nagios

   - name:     vagrant
     user:     name=vagrant  shell="{{ bash_shell }}"  uid=998  createhome=yes  group=vagrant   password=sobxtSZ2VA78Q
     when:     need_role_vagrant

   - name:     vboxadd
     user:     name=vboxadd  shell="{{ bash_shell }}"  uid=999  createhome=yes  group=daemon

   - name:     ioannis
     user:     name=ioannis  shell="{{ bash_shell }}" uid=1000 createhome=yes  group=ioannis

   - name:      postgres
     user:      name=postgres shell="{{ bash_shell }}" uid=1001 createhome=yes  group=postgres
     when:      need_role_postgres

   - name:      nagios
     user:      name=nagios   shell="{{ bash_shell }}"  uid=1002 createhome=yes  group=nagios
     when:      need_role_nagios
