## Assumes vars:  SHELL


## Add Groups

   - name:     group vagrant
     group:    name=vagrant  gid=998     state=present
     when:     need_role_vagrant

   - name:     group vboxsf
     group:    name=vboxsf    state=present

   - name:     group ioannis
     group:    name=ioannis   gid=1000
     when:     need_role_ioannis

   - name:     group postgres
     group:    name=postgres  gid=1001
     when:     need_role_postgres

   - name:     group nagios
     group:    name=nagios    gid=1002
     when:     need_role_nagios

## Add Users

   - name:     user vagrant
     user:     name=vagrant  shell="{{ SHELL }}"  uid=998  createhome=yes  group=vagrant   password=sobxtSZ2VA78Q
     when:     need_role_vagrant

   - name:     user vboxadd
     user:     name=vboxadd  shell="{{ SHELL }}"   createhome=yes  group=daemon

   - name:     user ioannis
     user:     name=ioannis  shell="{{ SHELL }}" uid=1000 createhome=yes  group=ioannis

   - name:     user postgres
     user:     name=postgres shell="{{ SHELL }}" uid=1001 createhome=yes  group=postgres
     when:     need_role_postgres

   - name:     user nagios
     user:     name=nagios   shell="{{ SHELL }}"  uid=1002 createhome=yes  group=nagios
     when:     need_role_nagios
