
- synchronize:  src="etc/apache2/"  dest="/etc/apach2/"  copy_links='yes'  owner=root

- name: htpasswd.users
  copy:  src="etc/apache2/htpasswd.users"  dest="/etc/apache2" owner='root' mode='0644'    force='yes' 

- name: htpasswd.users
  copy:  src="etc/apache2/htpasswd.nagios"  dest="/etc/apache2" owner='root' mode='0644'    force='yes' 

- name: untar apache2_etc.tar.gz
  when: false
  unarchive:
      src:            "etc/{{ item }}"
      dest:           '/etc/apache2-'
      owner:          root
      group:          root
  with_items:
      - apache2_etc.tar.gz

- name:  www pages  - links ( books, jbooks, tutorials)
  file:  src="{{ HOME }}/Shared/{{ item }}"  dest="/var/www/html/{{ item }}"   state=link    owner=www-data  group=www-data   force=yes
  with_items:
      - books
      - jbooks
      - tutorials



- name:  www pages  - links  (Postgres docs)
  file:  src="~postgres/dist-pg/share/doc/html"  dest="/var/www/html/Postgres"   state=link    owner=www-data  group=www-data  force=yes

