- name:  cgroup packages
  apt:
     pkg:
        - libcgroup1
        - cgroup-tools
        - cgroupfs-mount

- name:   mkdir /etc/cgroup
  file:   path="/etc/cgroup"        state=directory   force=yes  owner=root   mode=750

- name:  /root/cgroup 
  synchronize: src="etc/cgroup"  dest="/root/"   delete='no'  owner=no  dirs=yes  rsync_opts=--ignore-existing

- name:  cgconfig.conf
  copy:  src="etc/cgroup/cgconfig.conf"          dest="/etc"    owner=root  force=yes  mode=644

- name:  /etc
  copy:  src="etc/cgroup/{{ item }}"          dest="/etc/cgroup"   owner=root  force=yes  mode=644
  with_items:
      - rules.conf
      - makefile
      - cgred.conf

- name:  /etc/cgrules.conf
  file:   src="/etc/cgroup/rules.conf"         dest="/etc/cgrules.conf"     state=link  force=yes owner=root


####################################################  systemd
- name:       cgconfigparser.service
  copy:       src=etc/systemd/system/cgconfigparser.service   dest="/etc/systemd/system/"     owner=root

- name:       cgrulesgend.service
  copy:       src=etc/systemd/system/cgrulesgend.service     dest="/etc/systemd/system/"     owner=root

- systemd:    daemon_reload="yes"

