####################################################  packages
- name:           consul Key
  apt_key:
     #id:         '4E40DDF6D76E284A4A6780E48C8C34C524098CB6'
      url:       https://apt.releases.hashicorp.com/gpg 


- name:            consul Hashicorp.com epository
  apt_repository:  
     repo:        deb [arch=amd64] https://apt.releases.hashicorp.com buster main
     filename:    consul 


- name:          packages consul
  apt:
     name:          consul
     update_cache:  yes
####################################################  /etc/consul   FILES

- name: files
  include: consul/files.yml

- name: systemd
  include: consul/systemd.yml
