# pip  Pyrseas

#pip install --upgrade docutils

    - macports: name="ansible"           state=absent
    - macports: name="py36-ansible"      state=present
    - macports: name="apache2"
    - macports: name="apple-gcc42"
    - macports: name="apr"
    - macports: name="apr-util"
    - macports: name="ascii"
    - macports: name="asciidoc"
    - macports: name="aspell"
    - macports: name="aspell-dict-en"
    - macports: name="at-spi2-atk"
    - macports: name="at-spi2-core"
    - macports: name="atk"
    - macports: name="autoconf"
    - macports: name="autoconf-archive"
    - macports: name="automake"
    - macports: name="bison"
    - macports: name="bison"
    - macports: name="bison-runtime"
    - macports: name="bison-runtime"
    - macports: name="bzip2"
    - macports: name="cairo"
    - macports: name="cctools"
    - macports: name="cidr"
    - macports: name="clang-4.0"
    - macports: name="clang_select"
    - macports: name="cmake"
    - macports: name="ctags"
    - macports: name="curl"
    - macports: name="curl"
    - macports: name="curl-ca-bundle"
    - macports: name="curl-ca-bundle"
    - macports: name="curl-ca-bundle"
    - macports: name="cyrus-sasl2"
    - macports: name="cython_select"
    - macports: name="db46"
    - macports: name="db48"
    - macports: name="dbus"
    - macports: name="desktop-file-utils"
    - macports: name="docbook-dsssl"
    - macports: name="docbook-sgml-4.2"
    - macports: name="docbook-xml-4.2"
    - macports: name="docbook-xml-4.5"
    - macports: name="docbook-xsl"
    - macports: name="expat"
    - macports: name="fftw-3"
    - macports: name="figlet"
    - macports: name="flac"
    - macports: name="fontconfig"
    - macports: name="fop"
    - macports: name="fping"
    - macports: name="freeglut"
    - macports: name="freetype"
    - macports: name="gawk"
    - macports: name="gawk"
    - macports: name="gcc6"
    - macports: name="gcc_select"
    - macports: name="gd2"
    - macports: name="gdal"
    - macports: name="gdbm"
    - macports: name="gdbm"
    - macports: name="gdk-pixbuf2"
    - macports: name="geos"
    - macports: name="getopt"
    - macports: name="gettext"
    - macports: name="giflib"
    - macports: name="glib2"
    - macports: name="gmake"
    - macports: name="gmp"
    - macports: name="gnome-common"
    - macports: name="gnutls"
    - macports: name="gnutls"
    - macports: name="go"
    - macports: name="gobject-introspection"
    - macports: name="gpg-agent"
    - macports: name="graphite2"
    - macports: name="gsed"
    - macports: name="gsl"
    - macports: name="gtk3"
    - macports: name="harfbuzz"
    - macports: name="hicolor-icon-theme"
    - macports: name="icu"
    - macports: name="idutils"
    - macports: name="iftop"
    - macports: name="intltool"
    - macports: name="iperf3"
    - macports: name="isl"
    - macports: name="iso8879"
    - macports: name="jasper"
    - macports: name="jpeg"
    - macports: name="json-c"
    - macports: name="kerberos5"
    - macports: name="lcms2"
    - macports: name="ld64"
    - macports: name="ld64-latest"
    - macports: name="libao"
    - macports: name="libarchive"
    - macports: name="libart_lgpl"
    - macports: name="libassuan"
    - macports: name="libcaca"
    - macports: name="libcomerr"
    - macports: name="libcxx"
    - macports: name="libdbi"
    - macports: name="libdbi-drivers"
    - macports: name="libedit"
    - macports: name="libepoxy"
    - macports: name="libesmtp"
    - macports: name="libevent"
    - macports: name="libffi"
    - macports: name="libgcc"
    - macports: name="libgcrypt"
    - macports: name="libgcrypt"
    - macports: name="libgeoip"
    - macports: name="libgeotiff"
    - macports: name="libGLU"
    - macports: name="libgpg-error"
    - macports: name="libgpg-error"
    - macports: name="libiconv"
    - macports: name="libid3tag"
    - macports: name="libidl"
    - macports: name="libidn"
    - macports: name="libksba"
    - macports: name="libmad"
    - macports: name="libmagic"
    - macports: name="libmikmod"
    - macports: name="libmng"
    - macports: name="libmpc"
    - macports: name="libogg"
    - macports: name="libomp"
    - macports: name="libpcap"
    - macports: name="libpixman"
    - macports: name="libpng"
    - macports: name="libpng"
    - macports: name="libproj4"
    - macports: name="libsdl"
    - macports: name="libsdl_mixer"
    - macports: name="libtasn1"
    - macports: name="libtool"
    - macports: name="libunistring"
    - macports: name="libuv"
    - macports: name="LibVNCServer"
    - macports: name="libvorbis"
    - macports: name="libxml2"
    - macports: name="libxml2"
    - macports: name="libxslt"
    - macports: name="libyaml"
    - macports: name="llvm-3.9"
    - macports: name="llvm-4.0"
    - macports: name="llvm_select"
    - macports: name="lynx"
    - macports: name="lz4"
    - macports: name="lzo2"
    - macports: name="m4"
    - macports: name="m4"
    - macports: name="mesa"
    - macports: name="mhash"
    - macports: name="mod_wsgi"
    - macports: name="mpfr"
    - macports: name="mpg321"
    - macports: name="multitail"
    - macports: name="nagios"
    - macports: name="nagios-plugins"
    - macports: name="ncurses"
    - macports: name="nettle"
    - macports: name="nodejs4"
    - macports: name="nosetests_select"
    - macports: name="npm2"
    - macports: name="nrpe"
    - macports: name="nspr"
    - macports: name="nss"
    - macports: name="openjade"
    - macports: name="openldap"
    - macports: name="opensp"
    - macports: name="openssl"
    - macports: name="p5.24-cpan-meta"
    - macports: name="p5.24-cpan-meta-requirements"
    - macports: name="p5.24-cpan-meta-yaml"
    - macports: name="p5.24-crypt-cbc"
    - macports: name="p5.24-crypt-des"
    - macports: name="p5.24-crypt-rijndael"
    - macports: name="p5.24-digest-hmac"
    - macports: name="p5.24-digest-sha1"
    - macports: name="p5.24-encode"
    - macports: name="p5.24-encode-locale"
    - macports: name="p5.24-file-listing"
    - macports: name="p5.24-getopt-long"
    - macports: name="p5.24-html-form"
    - macports: name="p5.24-html-parser"
    - macports: name="p5.24-html-tagset"
    - macports: name="p5.24-http-cookies"
    - macports: name="p5.24-http-daemon"
    - macports: name="p5.24-http-date"
    - macports: name="p5.24-http-message"
    - macports: name="p5.24-http-negotiate"
    - macports: name="p5.24-inc-latest"
    - macports: name="p5.24-io-html"
    - macports: name="p5.24-io-socket-ssl"
    - macports: name="p5.24-libwww-perl"
    - macports: name="p5.24-lwp-mediatypes"
    - macports: name="p5.24-lwp-protocol-https"
    - macports: name="p5.24-mime-base64"
    - macports: name="p5.24-module-build"
    - macports: name="p5.24-module-metadata"
    - macports: name="p5.24-mozilla-ca"
    - macports: name="p5.24-net-http"
    - macports: name="p5.24-net-libidn"
    - macports: name="p5.24-net-snmp"
    - macports: name="p5.24-net-ssleay"
    - macports: name="p5.24-pathtools"
    - macports: name="p5.24-perl-ostype"
    - macports: name="p5.24-pod-escapes"
    - macports: name="p5.24-pod-simple"
    - macports: name="p5.24-podlators"
    - macports: name="p5.24-scalar-list-utils"
    - macports: name="p5.24-socket6"
    - macports: name="p5.24-sub-name"
    - macports: name="p5.24-sub-uplevel"
    - macports: name="p5.24-test-exception"
    - macports: name="p5.24-test-nowarnings"
    - macports: name="p5.24-test-warn"
    - macports: name="p5.24-try-tiny"
    - macports: name="p5.24-uri"
    - macports: name="p5.24-version"
    - macports: name="p5.24-www-robotrules"
    - macports: name="p5.24-xml-parser"
    - macports: name="p11-kit"
    - macports: name="pango"
    - macports: name="pcre"
    - macports: name="pdsh"
    - macports: name="perl5"
    - macports: name="perl5.18"
    - macports: name="perl5.18"
    - macports: name="perl5.24"
    - macports: name="php"
    - macports: name="php55"
    - macports: name="php55-apache2handler"
    - macports: name="php56"
    - macports: name="php56-apache2handler"
    - macports: name="php71"
    - macports: name="php_select"
    - macports: name="pinentry-mac"
    - macports: name="pinfo"
    - macports: name="pinfo"
    - macports: name="pip_select"
    - macports: name="pixz"
    - macports: name="pkgconfig"
    - macports: name="pkgconfig"
    - macports: name="popt"
    - macports: name="postgresql95"
    - macports: name="postgresql95"
    - macports: name="proj"
    - macports: name="protobuf-c"
    - macports: name="protobuf-cpp"
    - macports: name="pth"
    - macports: name="py27-appdirs"
    - macports: name="py27-appdirs"
    - macports: name="py27-asn1"
    - macports: name="py27-asn1crypto"
    - macports: name="py27-babel"
    - macports: name="py27-beaker"
    - macports: name="py27-certifi"
    - macports: name="py27-certifi"
    - macports: name="py27-cffi"
    - macports: name="py27-crypto"
    - macports: name="py27-cryptography"
    - macports: name="py27-cython"
    - macports: name="py27-enum34"
    - macports: name="py27-genshi"
    - macports: name="py27-httplib2"
    - macports: name="py27-idna"
    - macports: name="py27-ipaddress"
    - macports: name="py27-jinja2"
    - macports: name="py27-mako"
    - macports: name="py27-markupsafe"
    - macports: name="py27-nose"
    - macports: name="py27-numpy"
    - macports: name="py27-packaging"
    - macports: name="py27-paramiko"
    - macports: name="py27-parsing"
    - macports: name="py27-parsing"
    - macports: name="py27-pip"
    - macports: name="py27-pycparser"
    - macports: name="py27-pygments"
    - macports: name="py27-readline"
    - macports: name="py27-setuptools"
    - macports: name="py27-setuptools"
    - macports: name="py27-six"
    - macports: name="py27-sqlite"
    - macports: name="py27-tz"
    - macports: name="py27-yaml"
    - macports: name="python2_select"
    - macports: name="python3_select"
    - macports: name="python27"
    - macports: name="python27"
    - macports: name="python34"
    - macports: name="python_select"
    - macports: name="qhull"
    - macports: name="qt4-mac"
    - macports: name="rabbitmq-c"
    - macports: name="readline"
    - macports: name="readline"
    - macports: name="redis"
    - macports: name="rrdtool"
    - macports: name="sc"
    - macports: name="serf1"
    - macports: name="shared-mime-info"
    - macports: name="sipcalc"
    - macports: name="smpeg"
    - macports: name="sqlite3"
    - macports: name="sqlite3"
    - macports: name="subversion"
    - macports: name="subversion-python27bindings"
    - macports: name="tcl"
    - macports: name="tcp_wrappers"
    - macports: name="texinfo"
    - macports: name="tiff"
    - macports: name="tk"
    - macports: name="toilet"
    - macports: name="trac"
    - macports: name="vde2"
    - macports: name="vim"
    - macports: name="webp"
    - macports: name="wget"
    - macports: name="whatmask"
    - macports: name="wordnet"
    - macports: name="wxgtk-3.0"
    - macports: name="wxWidgets-common"
    - macports: name="wxWidgets_select"
    - macports: name="xar"
    - macports: name="Xft2"
    - macports: name="xhyve"
    - macports: name="xmlcatmgr"
    - macports: name="xmlsec"
    - macports: name="xorg-compositeproto"
    - macports: name="xorg-damageproto"
    - macports: name="xorg-dri2proto"
    - macports: name="xorg-fixesproto"
    - macports: name="xorg-glproto"
    - macports: name="xorg-inputproto"
    - macports: name="xorg-kbproto"
    - macports: name="xorg-libice"
    - macports: name="xorg-libpthread-stubs"
    - macports: name="xorg-libsm"
    - macports: name="xorg-libX11"
    - macports: name="xorg-libXau"
    - macports: name="xorg-libxcb"
    - macports: name="xorg-libXcomposite"
    - macports: name="xorg-libXcursor"
    - macports: name="xorg-libXdamage"
    - macports: name="xorg-libXdmcp"
    - macports: name="xorg-libXext"
    - macports: name="xorg-libXfixes"
    - macports: name="xorg-libXi"
    - macports: name="xorg-libXinerama"
    - macports: name="xorg-libXmu"
    - macports: name="xorg-libXrandr"
    - macports: name="xorg-libXScrnSaver"
    - macports: name="xorg-libXt"
    - macports: name="xorg-libXtst"
    - macports: name="xorg-libXxf86vm"
    - macports: name="xorg-randrproto"
    - macports: name="xorg-recordproto"
    - macports: name="xorg-renderproto"
    - macports: name="xorg-scrnsaverproto"
    - macports: name="xorg-xcb-proto"
    - macports: name="xorg-xcb-util"
    - macports: name="xorg-xextproto"
    - macports: name="xorg-xf86vidmodeproto"
    - macports: name="xorg-xineramaproto"
    - macports: name="xorg-xproto"
    - macports: name="xpm"
    - macports: name="xrender"
    - macports: name="xz"
    - macports: name="yarn"
    - macports: name="zlib"
    - macports: name="coreutils"
