
- include: "Linux-config.yml"

- include: pgbloat.yml

- include: ansible-Debian.yml
  when:     need_ansible

- include: grafana-Debian.yml
  when:    need_grafana

- include: prometheus-Debian.yml
  when:    need_prometheus

- include: loki-Linux.yml
  when:    need_loki

- include: promtail-Linux.yml
  when:    need_promtail

- include: fluentd-Debian.yml
  when:    need_fluentd

- include: pgspray-Debian.yml
  when:    need_pgspray

- include: fluent-bit-Debian.yml
  when:    need_fluent_bit

- include: grok_exporter-Debian.yml
  when:    need_grok_exporter

- include: consul-Debian.yml
  when:    need_consul

- include: stock_brokers.yml

- include: X11.yml



- include:       adobe.yml
  become_user:   root
  become:        yes
  when:          need_adobe_flash 

