
- name:           docker
  apt_key:
     id:         '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
     url:        https://download.docker.com/linux/debian/gpg


- name:            docker  repository
  apt_repository:
    repo:         deb http://download.docker.com/linux/debian buster stable
    filename:     docker-ce


- name:            docker
  apt:             
     pkg:
                   - apt-transport-https  
                   - ca-certificates 
                   - gnupg2 
                   - software-properties-common
                   - curl
                   - docker-ce 
                   - docker-ce-cli 
                   - containerd.io
                   - syntax-docker 
                   - docker-registry


- name:          Docker users
  when:          false
  shell:         usermod -aG docker ioannis
 

#TODO: IMPORTANT:  move file from /var/lib/docker/ to  ~ioannis/docker-data/. Then enable the task bellow.
- name:           /etc/docker
  when:           false
  synchronize:    src="/etc/docker/"  dest="/etc/docker"    rsync_opts=--ignore-existing

- name:          docker-composer
     uri:
       url:       https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
       dest:      /usr/local/bin/docker-compose
       creates:   /usr/local/bin/docker-compose
       timeout:   15
       mode:      0755

