- name:                 /etc/postfix/main.cf
  when:                 need_postfix
  blockinfile:
      insertbefore:     EOF
      path:             /etc/postfix/main.cf
      owner:            root
      block: |
          relayhost = [smtp.gmail.com]:587
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_tls_CAfile = /etc/postfix/cacert.pem
          smtp_use_tls = yes


- name:        /etc/postfix/sasl_passwd
  copy:        src="etc/postfix/{{ item }}"   dest="/etc/postfix/{{ item }}"    owner=root     mode=400
  when:        need_postfix
  with_items:
          - sasl_passwd
          - cacert.pem

- command:     '/sbin/postmap /etc/postfix/sasl_passwd'
  when:        need_postfix

- command:     '/etc/init.d/postfix reload'
  when:        need_postfix



- lineinfile:
    path: /etc/profile
    insertbefore: 'EOF'
    line: 'test -f /usr/local/bin/gmake && alias make=gmake'

- name: /etc/resolv.conf
  copy:  src="etc/resolv.conf"  dest="/etc/"  mode='0644' owner='root'   force='yes' 

- name: interfaces.d/*
  copy:  src="etc/network/interfaces.d/"  dest="/etc/network/interfaces.d/" owner='root' mode='0640'    force='no'
  when: os_family == 'Linux'


- name: ansible config and roles
  synchronize:  src="etc/ansible"  dest="/etc/"  copy_links='yes' delete='no'  owner='no'
  when: false


- name: influxdb, collectd, and grafana configs
  copy:  src="etc/influxdb"  dest="/etc/"  mode='0642' owner='ioannis'   force='yes' 


- name: sudoers
  copy:  src="etc/sudoers"  dest="/etc/" owner='root' mode='0640'    force='yes' 

- name: lynx config 
  copy:  src="etc/lynx"  dest="/etc/" owner='root' mode='0644'    force='yes' 

- name: lightdm
  copy:  src="etc/lightdm"  dest="/etc/" owner='root' mode='0644'    force='yes' 
  when: os_family == 'Linux'

- synchronize:  src="etc/lynx/lynx.cfg"  dest="/etc/"  copy_links='yes' 
