- lineinfile:
    path: /etc/profile
    insertbefore: 'EOF'
    line: 'test -f /usr/local/bin/gmake && alias make=gmake'

- name: /etc/resolv.conf
  copy:  src="etc/resolv.conf"  dest="/etc/"  mode='0644' owner='root'   force='yes' 

- name: interfaces.d/*
  copy:  src="etc/network/interfaces.d/"  dest="/etc/network/interfaces.d/" owner='root' mode='0640'    force='no'


- name: ansible config and roles
  synchronize:  src="etc/ansible"  dest="/etc/"  copy_links='yes' delete='no'  owner='no'
  when: false


- name: influxdb, collectd, and grafana configs
  copy:  src="etc/influxdb"  dest="/etc/"  mode='0642' owner='ioannis'   force='yes' 



- name: sudoers
  copy:  src="etc/sudoers"  dest="/etc/" owner='root' mode='0640'    force='yes' 

- name: lynx config 
  copy:  src="etc/lynx"  dest="/etc/" owner='root' mode='0644'    force='yes' 

- name: lightdm
  copy:  src="etc/lightdm"  dest="/etc/" owner='root' mode='0644'    force='yes' 

- synchronize:  src="etc/lynx/lynx.cfg"  dest="/etc/"  copy_links='yes' 
