
- name:           td-agent Key
  when: false
  apt_key:
      url:        https://ftp-master.debian.org/keys/archive-key-6.0.asc
      id:         '4FF8368B6EA0722A'

- shell:  wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add -


- name:            td-agent repository
  apt_repository:  repo="deb https://packages.fluentbit.io/ubuntu/bionic bionic main"



- name:            packages
  apt:
     pkg:
                 - td-agent-bit
####################################################  config files 
- name:         config files
  synchronize:  src=etc/td-agent-bit    dest="/etc/"    owner=root   delete='no'  owner=no  dirs=yes rsync_opts=--ignore-existing


####################################################  systemd
- name:        systemd file
  copy:        src=etc/systemd/system/td-agent-bit.service     dest="/etc/systemd/system/"     owner=root
  when:       false

####################################################  reload servers

- name:       reload  td-agent
  systemd:    name="td-agent-bit"   daemon_reload="yes"  state=stopped  enabled=no
  when:       
    - false
    - ansible_facts.services["td-agent-bit.service"].state  == 'disabled'

- name:       reload  td-agent
  systemd:    name="td-agent-bit"   daemon_reload="yes"  state=restarted  enabled=no
  when:       
    - false
    - ansible_facts.services["td-agent-bit.service"].state  == 'running'
