#############################  packages
- name:            packages
  apt:
     pkg:
                 - ruby2.5-dev
                 - postgresql-server-dev-11

#############################  install fluentd(1)
- name:         install fluentd(1)
  gem:
    name: fluent
    state: present

- name:         install fluent-plugin-grafana-loki
  gem:
    name: fluent-plugin-grafana-loki
    state: present

    
- name:   fluent-plugin-postgres
  gem:
    name: fluent-plugin-postgres
    state: present
    #environment:
    #- PGCONFIG:  /home/postgres/dist-pg/bin/pg_config

####################################################  symlinks 
- name:    symlink loki 
  file:    src='/root/.gem/ruby/2.5.0/gems/fluentd-1.11.2/bin/fluentd'   dest='/usr/local/bin/fluentd'   state=link  owner=root   force=yes


####################################################  config
- name:  fluent.conf#
  copy:  src="etc/loki/fluent.conf"  dest="/etc/loki"   owner=root  mode=640

####################################################  systemd
- name:        systemd file
  copy:        src=etc/systemd/system/fluentd.service     dest="/etc/systemd/system/"     owner=root
####################################################  reload servers
- systemd:    daemon_reload="yes"
- wait_for:    delay=3 timeout=0

- name:        set service 
  block:
      - systemd:    name="fluentd"   daemon_reload="yes"  state=stopped  enabled=no
        when:       ansible_facts.services["fluentd.service"].state  == 'disabled'
  rescue:
     - wait_for:    delay=10 timeout=0
      - systemd:    name="fluentd"   daemon_reload="yes"  state=stopped  enabled=no
        when:       ansible_facts.services["fluentd.service"].state  == 'disabled'


- name:       reload  fluentd
  systemd:    name="fluentd"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["fluentd.service"].state  == 'running'
  
# firewall-cmd --add-port=9880/tcp --permanent    ( not sure about port number)
