

- name:            grafana BETA repository
  blockinfile:
      insertbefore:     EOF
      path:             /etc/yum.repos.d/grafana.repo
      owner:            root
      create:           yes
      block: |
                [grafana]
                name=grafana
                baseurl=https://packages.grafana.com/oss/rpm
                repo_gpgcheck=1
                enabled=1
                gpgcheck=1
                gpgkey=https://packages.grafana.com/gpg.key
                sslverify=1
                sslcacert=/etc/pki/tls/certs/ca-bundle.crt

- name:  update yum
  yum: 
     update_cache: yes
     autoremove:   yes

- name:  packages
  yum:
     enablerepo: grafana
     name:
                 - grafana
 
#- command: yum -y --allowerasing upgrade  grafana

##############################################################################################

- name: grafana files
  include: grafana/files.yml

################################################################  systemd
- name: systemd
  include: grafana/systemd.yml

