
- name:           Grafana Key
  apt_key:
      id:         '4E40DDF6D76E284A4A6780E48C8C34C524098CB6'
      url:        https://packages.grafana.com/gpg.key

- name:            grafana repository
  when:            false
  apt_repository:  
       repo:       deb https://packages.grafana.com/oss/deb stable main  
       filename:   grafana

- name:            grafana BETA repository
  apt_repository:  
      repo:        deb https://packages.grafana.com/oss/deb beta main  
      filename:    grafana

- name:            packages
  apt:
     pkg:
                 - software-properties-common
                 - apt-transport-https
                 - libfontconfig1
                 - grafana
##############################################################################################

- name: grafana files
  include: grafana/files.yml

################################################################  systemd
- name: systemd
  include: grafana/systemd.yml
