####################################################  packages
# NOTE: prerequisites: prometheus already installed

####################################################  /etc/prometheus   FILES
#
- name:        check for grok_exporter(1)
  stat:        path="/usr/local/bin/grok_exporter"
  register:    grokbin

- include:     "compile/compile_grok_exporter-{{os_family}}.yml"
  when:         not grokbin.stat.exists

- name:        again, check for grok_exporter(1)
  stat:        path="/usr/local/bin/grok_exporter"
  register:    grokbin

- name:        assert /usr/local/bin/grok_exporter
  assert:       
    that:
        - grokbin.stat.exists
    quiet:      true
    fail_msg:   'please install grok_exporter(1)'

- name:         chmod 755 usr/local/bin/grok_exporter
  file:         path=/usr/local/bin/grok_exporter  mode=755

####################################################   systemd
- name:        systemd files
  copy:        src=etc/systemd/system/{{item}}     dest="/etc/systemd/system/"     owner=root
  with_items:
      - grok_exporter.service  
      - grok_exporter_karat.service 


####################################################   reload servers
- name:       reload  daemon
  systemd:    daemon_reload="yes"

- name:       reload  grok
  systemd:    name="grok_exporter"   daemon_reload="yes"  state=stopped  enabled=no
  when:       ansible_facts.services["grok_exporter.service"].state  == 'disabled'


- name:       reload  grok karat
  systemd:    name="grok_exporter_karat"   daemon_reload="yes"  state=stopped  enabled=no
  when:       ansible_facts.services["grok_exporter_karat.service"].state  == 'disabled'

- name:       reload  grok
  systemd:    name="grok_exporter"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["grok_exporter.service"].state  == 'running'

- name:       reload  grok karat
  systemd:    name="grok_exporter_karat"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["grok_exporter_karat.service"].state  == 'running'
