- name:            ubuntu.com  keyserver
  apt_key:         keyserver='http://keyserver.ubuntu.com'   id='EA8CACC073C3DB2A'

- name:            grafana.asc
  shell:           wget -q -O - https://packages.grafana.com/gpg.key  |  apt-key add -


- name:            docker.asc
  when:            need_docker
  apt_key:         data="{{ lookup('file', 'docker.asc') }}"   

- name:            oracle_vbox_2016.asc
  when:            allow_vbox_repo
  apt_key:         data="{{ lookup('file', 'oracle_vbox_2016.asc') }}"   
            
- name:            vbox keys
  shell:           apt-key  adv --keyserver keyserver.vbox.com  --recv-keys  A2F683C52980AECF
  when:            false

- name:            ubuntu bionic  repository
  when:     false
  apt_repository:  repo="deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main"    state='present'

- name:           grafana & slack repository
  copy:           src="etc/apt/{{ item }}"  dest="/etc/apt/sources.list.d/{{ item }}" owner=root  mode=644
  with_items:
      - grafana.list
      - slack.list

- name:            timescaledb  repository
  apt_repository:  repo="ppa:timescale/timescaledb-ppa"
  when:   false



- name:            virtualbox repo
  when:            allow_vbox_repo
  apt_repository:  repo="deb http://download.virtualbox.org/virtualbox/debian stretch contrib"    

- name:            Docker repo
  when:   false
  #when:            need_docker
  apt_repository:  repo="deb http://download.docker.com/linux/debian buster stable"    



- name:            apt_repository virtualbox
  when:            allow_contrib
  apt_repository:  repo="deb http://httpredir.debian.org/debian/ stable main contrib" 


- name:            virtualbox-5.1
  when:            allow_vbox_repo
  apt:             pkg=virtualbox-5.1    update_cache=yes      


- name:            update_cache" if the last one is more than 3600 seconds ago
  apt:             update_cache=yes   cache_valid_time=3600

- name:            python
  apt:
     pkg:
                  - python-apt
                  - python-pip
                  - python-psycopg2
                  - python3-apt
                  - python3-pip
                  - python3-psycopg2


- apt:     
     pkg:
                   - rsync
                   - make
                   - console-setup
                   - curl
                   - git
                   - aptitude
                   - lynx
                   - fping
                   - ascii
                   - ansible
                   - slapd
                   - w3m
                   - mpg123


- name:            xorg
  apt:             
     pkg:
                   - xfce4
                   - xfconf
                   - libinput10     
                   - lightdm

- name:            zfs 
  when:            zfs
  apt:             
     pkg:
                   - zfs-fuse
                   - zfsnap


- name:           Install pgxnclient
  apt:            pkg=pgxnclient     

- name:            java12
  ignore_errors:   yes
  apt:             
     pkg:
                   - oracle-java12-installer     
                   - oracle-java12-set-default


- name:            docker
  when:            need_docker
  apt:             
     pkg:
                   - apt-transport-https  
                   - docker-ce 


- name:            mail
  apt:
     pkg:
                  - postfix
                  - mailutils
                  - libsasl2-2
                  - ca-certificates
                  - libsasl2-modules
                  - mutt
                  - fetchmail
                  - feh
                  - urlview 
                  - xpdf
                  - abook
                  - libfontconfig1
                  - grafana
                  - collectd

- name:           snapd
  apt:            pkg=snapd
  when:           need_slack

- name:          Slack 
  when:          need_slack
  shell:         snap install slack-term

- name:          Slack 
  when:          need_slack
  shell:         snap install slack  --classic


- name:           apache2
  apt:            pkg=apache2
  when:           need_apache

- name:          prometheus 
  when:          need_prometheus
  apt:
     pkg:
                  - prometheus-blackbox-exporter 
                  - prometheus 
                  - protheus-postgres-exporter
                  - protheus-pgbouncer-exporter
                  - protheus-node-exporter
                  - prometheus-pushgateway 
                    #- prometheus-apache-exporter
                  - pgbouncer
                  - prometheus-alertmanager

