- name:            Add add-apt-repository
  apt:             pkg=software-properties-common

- name:           Google, Inc. (Linux Package Signing Authority)
  apt_key:
       id:       'EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796'
       url:      https://dl.google.com/linux/linux_signing_key.pub
       state:    present


- name:           Google, Inc. Linux Package Signing Key
  apt_key:
       id:         '4CCA1EAF950CEE4AB83976DCA040830F7FAC5991'
       url:        https://dl.google.com/linux/linux_signing_key.pub

#- name:            ubuntu.com  keyserver
#  apt_key:         keyserver='http://keyserver.ubuntu.com'   id='EA8CACC073C3DB2A'

- name:           Grafana Key
  apt_key:
      id:         '4E40DDF6D76E284A4A6780E48C8C34C524098CB6'
      url:        https://packages.grafana.com/gpg.key

- name:            docker.asc
  when:            need_docker
  apt_key:         data="{{ lookup('file', 'docker.asc') }}"   

- name:            oracle_vbox_2016.asc
sudo add-apt-repository ppa:linuxuprising/java
  when:            allow_vbox_repo
  apt_key:         data="{{ lookup('file', 'oracle_vbox_2016.asc') }}"   

            
- name:            vbox keys
  shell:           apt-key  adv --keyserver keyserver.vbox.com  --recv-keys  A2F683C52980AECF
  when:            false

- name:            oracle_java
  shell:           apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 73C3DB2A
  when:            oracle_java

- name:            oracle_java
  shell:           echo "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu focal main" >  /etc/apt/sources.list.d/linuxuprising-java.list
  when:            oracle_java

- name:            java-zulu keys
  shell:           apt-key  adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
  when:            thinkorswim

- name:            java-zulu  zulu.list
  shell:           echo 'deb http://repos.azulsystems.com/debian stable main' > /etc/apt/sources.list.d/zulu.list
  when:            thinkorswim

- name:            java-zulu-8 package
  apt:             pkg=zulu-8      update_cache=yes
  when:            thinkorswim

- name:            ubuntu bionic  repository
  when:            false
  apt_repository:  repo="deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main"    state='present'

- name:            grafana repository
  apt_repository:  repo="deb https://packages.grafana.com/oss/deb stable main"  

- name:            grafana BETA repository
  when:            false
  apt_repository:  repo="deb https://packages.grafana.com/oss/deb beta main"  

- name:           slack repository
  copy:           src="etc/apt/{{ item }}"  dest="/etc/apt/sources.list.d/{{ item }}" owner=root  mode=644
  with_items:
      - slack.list

- name:            timescaledb  repository
  apt_repository:  repo="ppa:timescale/timescaledb-ppa"
  when:   false



- name:            virtualbox repo
  when:            allow_vbox_repo
  apt_repository:  repo="deb http://download.virtualbox.org/virtualbox/debian stretch contrib"    

- name:            Docker repo
  when:            false
  #when:            need_docker
  apt_repository:  repo="deb http://download.docker.com/linux/debian buster stable"    



- name:            apt_repository virtualbox
  when:            allow_contrib
  apt_repository:  repo="deb http://httpredir.debian.org/debian/ stable main contrib" 


- name:            virtualbox-5.1
  when:            allow_vbox_repo
  apt:             pkg=virtualbox-5.1    update_cache=yes      


- name:            update_cache" if the last one is more than 3600 seconds ago
  when:            false
  apt:             update_cache=yes   cache_valid_time=3600

- name:            python
  apt:
     pkg:
                  - python-apt
                  - python-pip
                  - python-psycopg2
                  - python3-apt
                  - python3-pip
                  - python3-psycopg2


- apt:     
     pkg:
                   - rsync
                   - make
                   - console-setup
                   - curl
                   - git
                   - aptitude
                   - lynx
                   - fping
                   - ascii
                   - ansible
                   - slapd
                   - w3m
                   - mpg123
                   - lm-sensors
                   - sc
                   - info
                   - beep
                   - wordnet
                   - dc 
                   - bc 
                   - openssh-server

- name:            xorg
  apt:             
     pkg:
                   - xfce4
                   - xfconf
                   - libinput10     
                   - lightdm
                   - xfce4-screenshooter
                   - xfce4-battery-plugin
                   - xfce-keyboard-shortcuts
                   - xfce4-systemload-plugin
                   - xfce4-weather-plugin
                   - flashrom 
                   - node-flashproxy 
                   - flashproxy-client 
                   - get-flash-videos


- name:            zfs 
  when:            zfs
  apt:             
     pkg:
                   - zfs-fuse
                   - zfsnap


- name:           Install pgxnclient
  apt:            pkg=pgxnclient     

- name:            oracle_java
  ignore_errors:   yes
  when:            oracle_java
  apt:             
     pkg:
                   - oracle-java14-installer     
                   - oracle-java14-set-default
                   - icedtea-netx


- name:            docker
  when:            need_docker
  apt:             
     pkg:
                   - apt-transport-https  
                   - docker-ce 


- name:            mail
  apt:
     pkg:
                  - postfix
                  - vim-gtk
                  - mailutils
                  - libsasl2-2
                  - ca-certificates
                  - libsasl2-modules
                  - mutt
                  - fetchmail
                  - feh
                  - urlview 
                  - xpdf
                  - abook
                  - libfontconfig1
                  - grafana
                  - collectd

- name:           snapd
  apt:            pkg=snapd
  when:           need_slack

- name:          Slack 
  when:          need_slack
  shell:         snap install slack-term

- name:          Slack 
  when:          need_slack
  shell:         snap install slack  --classic


- name:           libappindicator3
  apt:            pkg=libappindicator3
  when:           need_slack

- name:           apache2
  apt:            pkg=apache2
  when:           need_apache

- name:          pgbouncer
  when:          need_pgbouncer
  apt:           pkg=pgbouncer

- name:          perl
  apt:
     pkg:
                  - libfile-slurp-perl
                  - libdata-show-perl

- name:          prometheus 
  when:          need_prometheus
  apt:
     pkg:
                  - prometheus-blackbox-exporter 
                  - prometheus 
                  - prometheus-postgres-exporter
                  - prometheus-pgbouncer-exporter
                  - prometheus-node-exporter
                  - prometheus-pushgateway 
                  - prometheus-apache-exporter
                  - pgbouncer
                  - prometheus-alertmanager
                  - consul

