- name: vim valternative
  alternatives:
       name: vi
       path: "{{ item }}"
       priority: 10
  with_first_found:
       - /bin/vim.tiny
       - /usr/bin/vim.tiny
       - /bin/vim.basic
       - /usr/bin/vim.basic
       - /bin/vim
       - /usr/bin/vim



- name: editor alternative
  alternatives:
       name:   editor
       path:  "{{ item }}"
       priority: 10
  with_first_found:
       - files:
           - /usr/bin/vim.tiny
           - /bin/vim.tiny
           - /usr/bin/vim
           - /bin/vim
         skip: true


- name: python altenative 2.7
  alternatives:
       name: python
       link: /usr/bin/python
       path: /usr/bin/python2.7
       priority: 4

# because ansibile sets last alternative as the 'manual' default
- name: python altenative 3.7
  alternatives:
       name: python
       link: /usr/bin/python
       path: /usr/bin/python3.7
       priority: 10

- name: set java
  when: thinkorswim
  alternatives: name=java  path=/usr/lib/jvm/zulu-8-amd64/jre/bin/java


- name: set javac
  when: thinkorswim
  alternatives: name=javac  path=/usr/lib/jvm/zulu-8-amd64/bin/javac


- name:  link /Users 
  file:  src=/home  dest=/Users  state=link  owner=root 
