- name:            ubuntu.com  keyserver
  apt_key:         keyserver='http://keyserver.ubuntu.com'   id='EA8CACC073C3DB2A'

- name:            ubuntu bionic  repository
  apt_repository:  repo="deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main"    state='present'

- name:            docker.asc
  when:            need_docker
  apt_key:         data="{{ lookup('file', 'docker.asc') }}"   

- name:            oracle_vbox_2016.asc
  when:            allow_vbox_repo
  apt_key:         data="{{ lookup('file', 'oracle_vbox_2016.asc') }}"   
            
- name:            vbox keys
  shell:           apt-key  adv --keyserver keyserver.vbox.com  --recv-keys  A2F683C52980AECF
  when:            false

- name:            virtualbox repo
  when:            allow_vbox_repo
  apt_repository:  repo="deb http://download.virtualbox.org/virtualbox/debian stretch contrib"    

- name:            Docker repo
  when:            need_docker
  apt_repository:  repo="deb http://download.docker.com/linux/debian buster stable"    



- name:            apt_repository virtualbox
  when:            allow_contrib
  apt_repository:  repo="deb http://httpredir.debian.org/debian/ stable main contrib" 


- name:            virtualbox-5.1
  when:            allow_vbox_repo
  apt:             pkg="virtualbox-5.1"    update_cache='yes'      


- name:           Install python-apt
  apt:            pkg="python-apt"        

- name:           Install python3-apt
  apt:            pkg="python3-apt"        update_cache="yes"

- name:           Install rsync
  apt:            pkg="rsync"              

- name:           Install make
  apt:            pkg="make"           

- name:           Install console-setup
  apt:            pkg="console-setup"  

- name:           Install sudo
  apt:            pkg="sudo"          

- name:           Install curl
  apt:            pkg="curl"       

- name:           Install git
  apt:            pkg="git"       
  register:       git_present

- name:           Install zfs-fuse
  apt:            pkg="zfs-fuse" 
  when:           zfs

- name:           Install lynx
  apt:            pkg="lynx"    

- name:           Install aptitude
  apt:            pkg="aptitude"    

- name:           Install zfsnap
  when:           zfs
  apt:            pkg="zfsnap"       

- name:           Install fping
  apt:            pkg="fping"         

- name:           Install pgxnclient
  apt:            pkg="pgxnclient"     

  #  psycopg2 needed by postgres module
- name:           Install psycopg2
  apt:            pkg="python-psycopg2" 

- name:           Install xfce4
  apt:            pkg="xfce4"        

- name:           Install xfconf
  apt:            pkg="xfconf"        

- name:           Install libinput10
  apt:            pkg="libinput10"     

- name:           lightdm in effect
  shell:          dpkg-reconfigure lightdm

- name:           java12
  apt:            pkg="oracle-java12-installer"     
  ignore_errors:  yes

- apt:           pkg="oracle-java12-set-default"
  ignore_errors: yes

- apt:           pkg="ascii"

- name:          Docker related
  when:          need_docker
  apt:           pkg="apt-transport-https"     

- name:          Docker
  when:          need_docker
  apt:           pkg="docker-ce"     

- name:          Slack related
  when:          need_slack
  apt:           pkg="slapd"

- name:          Slack 
  when:          need_slack
  shell:         snap install slack-term
  when:          false

- name:          Slack 
  when:          need_slack
  shell:         snap install slack
  when:          false
