#############################  install  loki(1) and logcli(1)
- name:         install loki(1)
  unarchive:
      src:          "https://github.com/grafana/loki/releases/download/{{LOKI_RELEASE}}/loki-linux-amd64.zip"
      dest:         /tmp/
      remote_src:   yes
      creates:      /usr/local/bin/loki-linux-amd64 

- command:       cp -a "/tmp/loki-linux-amd64"  "/usr/local/bin/"  
  args:
      creates:       /usr/local/bin/loki-linux-amd64 
######
- name:         install logcli(1)
  unarchive:
      src:          "https://github.com/grafana/loki/releases/download/{{LOKI_RELEASE}}/logcli-linux-amd64.zip"
      dest:         /tmp/
      remote_src:   yes
      creates:      /usr/local/bin/logcli-linux-amd64 

- command:       cp -a "/tmp/logcli-linux-amd64"  "/usr/local/bin/"  
  args:
      creates:       /usr/local/bin/logcli-linux-amd64 
##############################################  check both intalls
- name:        check for loki(1)
  stat:        path="/usr/local/bin/loki-linux-amd64"
  register:    lokibin

- name:        assert /usr/local/bin/loki-linux-amd64
  assert:       
    that:
        - lokibin.stat.exists
    quiet:      true
    fail_msg:   'please install loki-linux-amd64r(1)'

- name:        check for logcli(1)
  stat:        path="/usr/local/bin/logcli-linux-amd64"
  register:    logclibin


- name:        assert /usr/local/bin/logcli-linux-amd64
  assert:       
    that:
        - logclibin.stat.exists
    quiet:      true
    fail_msg:   'please install logcli-linux-amd64r(1)'

####################################################  symlinks 
- name:    symlink loki 
  file:    src='/usr/local/bin/loki-linux-amd64'   dest='/usr/local/bin/loki'   state=link  owner=root   force=yes

- name:    symlink logcli
  file:    src='/usr/local/bin/logcli-linux-amd64'   dest='/usr/local/bin/logcli'   state=link  owner=root   force=yes
####################################################  config files 
- name:         config files
  synchronize:  src=etc/loki    dest="/etc/"    owner=root   delete='no'  owner=no  dirs=yes rsync_opts=--ignore-existing


####################################################  systemd
- name:        systemd file
  copy:        src=etc/systemd/system/loki.service     dest="/etc/systemd/system/"     owner=root
  when:        os_family == 'Linux'

- name:       reload  loki
  when:       os_family == 'Linux' 
  systemd:    name="loki"   daemon_reload="yes"  state=started  enabled=yes
