#- name: Populate service facts
#  service_facts:
################################## Helper Variables
- shell:  uname -s
  register: result

- set_fact: os_family="{{result.stdout}}"

- set_fact: 
      HOME:  "/home"
      SHELL: "/bin/bash"
  when:  os_family == "Linux"
  # ansible_os_family -> RedHat, Debian
  
- set_fact: 
      HOME:  "/Users"
      SHELL: "/bin/bash"
  when:  os_family == "Darwin"

- set_fact: 
     HOME:   "/home"
     SHELL:  "/usr/local/bin/bash"
  when:  os_family == "FreeBSD"

- set_fact: need_pgbouncer = true
  when:     need_prometheus
#################################################     M A I N
     
- include:  ansible-Debian.yml
  #- include:  grafana-RedHat.yml
 #- include:  docker.yml
 #- include:  loki-Linux.yml
 #- include:  pgspray-Debian.yml
 #- include:  pgbloat.yml
#- include:  prometheus-RedHat.yml
#- include: grok_exporter-Linux.yml

