################################## Helper Variables
- shell:  uname -s
  register: result

- set_fact: os_family="{{result.stdout}}"

- set_fact: 
      HOME:  "/home"
      SHELL: "/bin/bash"
  when:  os_family == "Linux"

- set_fact: 
      HOME:  "/Users"
      SHELL: "/bin/bash"
  when:  os_family == "Darwin"

- set_fact: 
     HOME:   "/home"
     SHELL:  "/usr/local/bin/bash"
  when:  os_family == "FreeBSD"

- set_fact: need_pgbouncer = true
  when:     need_prometheus
#################################################     M A I N
     
#- include: "loki-{{os_family}}.yml"
#- include: "promtail-{{os_family}}.yml"
#- include: fluentd-{{os_family}}.yml
- include:  fluent-bit-{{os_family}}.yml

