################################## Helper Variables
- shell:  uname -s
  register: result

- set_fact: os_family="{{result.stdout}}"

- set_fact: 
      HOME:  "/home"
      SHELL: "/bin/bash"
  when:  os_family == "Linux"

- set_fact: 
      HOME:  "/Users"
      SHELL: "/bin/bash"
  when:  os_family == "Darwin"

- set_fact: 
     HOME:   "/home"
     SHELL:  "/usr/local/bin/bash"
  when:  os_family == "FreeBSD"

#################################################     M A I N
     
- include: zfs.yml
  when:    zfs and (os_family != "Darwin")

- include: account.yml
  #vars:
      #- bash_shell: /usr/local/bin/bash

- include: ssh.yml

- include: "{{ os_family }}.yml"

- include: "Linux-config.yml"
  when:  os_family == "Linux"

- include: hosts.yml
  when: false

- include: etc.yml

- include: X11.yml
  when: os_family == 'Linux'

- include: var.yml

- include: cron.yml

##############################################  POST INSTALL
# Host-specific files (if available)
- include:   "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_hostname }}.yml"
      skip: true
