####################################################  packages
- name:          packages DBI, Getopts-Std, Timehires
  apt:
     pkg:
        - libdbi-perl
        - libtime-hires-perl
        - libdbd-pg-perl
        - libnet-prometheus-perl
          #- libplack-perl
          # libparallel-forkmanager-perl
        #plus   LWP::Useragent

####################################################  /etc/consul   FILES
#- name:        Files   /etc/prometheus/exporters/pgspray/*

- name:            /usr/local/bin/pgspray
  synchronize:     src=pgspray/ dest=/usr/local/bin/   delete=no  owner=no  rsync_opts=--exclude=secret

####################################################  /etc/prometheus/exporters
- name:       secret file
  copy:       src=pgspray/secret    dest=/etc/prometheus/exporters/    owner=prometheus    mode=420

####################################################  symlinks 
#- name:    data directory 
#  when:    os_family  == 'Darwin'  
#  file:    path="/var/lib/consul"    state=directory   owner=ioannis   force=yes
####################################################  /etc/default
- name:        /etc/default/pgspray
  copy:       src=etc/default/pgspray    dest=/etc/default/pgspray    owner=root   
####################################################   reload servers
- name:        systemd file
  copy:        src=etc/systemd/system/pgspray.service     dest="/etc/systemd/system/"     owner=root
  when:        os_family == 'Linux'

- name:        systemd file
  copy:        src=etc/systemd/system/pgspray_psgi.service     dest="/etc/systemd/system/"     owner=root
  when:        os_family == 'Linux'

- name:       reload  pgspray
  when:       os_family  == 'Linux'  
  systemd:    name="pgspray"   daemon_reload="yes"  state=stopped  enabled=no

- name:       reload  pgspray_psgi
  when:       os_family  == 'Linux'  
  systemd:    name="pgspray_psgi"   daemon_reload="yes"  state=stopped  enabled=no
