##################################################  packages
- name:          packages DBI, Getopts-Std, Timehires
  apt:
     pkg:
        - libdbi-perl
        - libtime-hires-perl
        - libdbd-pg-perl
        - libnet-prometheus-perl
        - libplack-perl
        - libparallel-forkmanager-perl

####################################################  /etc/consul   FILES
- name:    verify perl prereqs 
  command: perl -m{{item}} -e 'print 1'
  with_items:
            - Time::HiRes
            - DBI
            - DBD::Pg
            - Net::Prometheus
            - Parallel::ForkManager
            - LWP::UserAgent
            - Config::INI::Reader
            - Getopt::Compact
            - File::Slurp
            - Plack

####################################################  pgspray binaries
- name:            /usr/local/bin/pgspray
  synchronize:     src=pgspray/ dest=/usr/local/bin/   delete=no  owner=no  rsync_opts=--exclude=secret

####################################################  /etc/prometheus/exporters
- name:       secret file
  copy:       src=pgspray/secret    dest=/etc/prometheus/exporters/    owner=prometheus    mode=420

####################################################  symlinks 
#- name:    data directory 
#  file:    path="/var/lib/consul"    state=directory   owner=ioannis   force=yes
####################################################  /etc/default
- name:        /etc/default/pgspray
  copy:       src=etc/default/pgspray    dest=/etc/default/pgspray    owner=root   
  
####################################################   systemd

- name:       systemd
  include:    pgspray/systemd.yml

