####################################################  packages
- name:          packages DBI, Getopts-Std, Timehires
  apt:
     pkg:
        - libdbi-perl
        - libtime-hires-perl
        - libdbd-pg-perl
        - libnet-prometheus-perl
        - libplack-perl
        - libparallel-forkmanager-perl

####################################################  /etc/consul   FILES
- name:    verify perl prereqs 
  command: perl -m{{item}} -e 'print 1'
  with_items:
            - Time::HiRes
            - DBI
            - DBD::Pg
            - Net::Prometheus
            - Parallel::ForkManager
            - LWP::UserAgent
            - Config::INI::Reader
            - Getopt::Compact
            - File::Slurp
            - Plack

####################################################  /etc/consul   FILES
- name:            /usr/local/bin/pgspray
  synchronize:     src=pgspray/ dest=/usr/local/bin/   delete=no  owner=no  rsync_opts=--exclude=secret

####################################################  /etc/prometheus/exporters
- name:       secret file
  copy:       src=pgspray/secret    dest=/etc/prometheus/exporters/    owner=prometheus    mode=420

####################################################  symlinks 
#- name:    data directory 
#  when:    os_family  == 'Darwin'  
#  file:    path="/var/lib/consul"    state=directory   owner=ioannis   force=yes
####################################################  /etc/default
- name:        /etc/default/pgspray
  copy:       src=etc/default/pgspray    dest=/etc/default/pgspray    owner=root   
####################################################   systemd
- name:        install systemd file
  copy:        src=etc/systemd/system/pgspray.service     dest="/etc/systemd/system/"     owner=root

- name:        install systemd file  
  copy:        src=etc/systemd/system/pgspray_psgi.service     dest="/etc/systemd/system/"     owner=root

####################################################   reload servers
- name:       reload  pgspray
  no_log:     true
  systemd:    name="pgspray"   daemon_reload="yes"  state=stopped  enabled=no
  when:       ansible_facts.services["pgspray.service"].state  == 'disabled'

- name:       reload  pgspray_psgi
  no_log:     true
  systemd:    name="pgspray_psgi"   daemon_reload="yes"  state=stopped  enabled=no
  when:       ansible_facts.services["pgspray_psgi.service"].state  == 'disabled'

- name:       reload  pgspray
  no_log:     true
  systemd:    name="pgspray"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["pgspray.service"].state  == 'running'

- name:       reload  pgspray_psgi
  no_log:     true
  systemd:    name="pgspray_psgi"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["pgspray_psgi.service"].state  == 'running'
  #
