####################################################  packages
- name:          packages DBI, Getopts-Std, Timehires
  yum:
      name: 
         - perl-App-cpanminus
         - perl-Time-HiRes
         - perl-File-Slurp
         - perl-DBI
         - perl-DBD-Pg
         - perl-libwww-perl
         #- perl-Date-CalcXML

- name:           Config::INI
  command:        cpan -f Config::INI
  args:
     creates:    /usr/local/share/perl5/Config/INI

- name:           Net::Prometheus
  command:        cpan -f  Net::Prometheus
  args:
     creates:     /usr/local/share/perl5/Net/Prometheus

- name:           Parallel::ForkManager 
  command:        cpan -f  Parallel::ForkManager
  args:
     creates:     /usr/local/share/perl5/Parallel/ForkManager.pm

- name:           Plack
  command:        cpan -f  Plack
  args:
     creates:     /usr/local/bin/plackup

- name:          Getopt::Compact
  command:       cpan -f  Getopt::Compact
  args:
     creates:    /usr/local/share/perl5/Getopt/Compact
  
- name:    rm -rf ~root/.cpan/
  file :   dest=/root/.cpan     state=absent   force=yes

####################################################  pgspray binaries
- name:            /usr/local/bin/pgspray
  synchronize:     src=pgspray/ dest=/usr/local/bin/   delete=no  owner=no  rsync_opts=--exclude=secret

####################################################  /etc/prometheus/exporters
- name:       secret file
  copy:       src=pgspray/secret    dest=/etc/prometheus/exporters/    owner=prometheus    mode=420

####################################################  symlinks 
#- name:    data directory 
#  file:    path="/var/lib/consul"    state=directory   owner=ioannis   force=yes
####################################################  /etc/default
- name:        /etc/default/pgspray
  copy:       src=etc/default/pgspray    dest=/etc/default/pgspray    owner=root   
####################################################   systemd
#
- name:       systemd
  include:    pgspray/systemd.yml

