#############################  install  loki(1) and logcli(1)
- name:         install loki(1)
  unarchive:
      src:          "https://github.com/grafana/loki/releases/download/{{LOKI_RELEASE}}/promtail-linux-amd64.zip"
      dest:         /tmp/
      remote_src:   yes
      creates:      /usr/local/bin/promtail-linux-amd64 

- command:       cp -a "/tmp/promtail-linux-amd64"  "/usr/local/bin/"  
  args:
      creates:       /usr/local/bin/promtail-linux-amd64 
      
##############################################  check intallation
- name:        check for promtail(1)
  stat:        path="/usr/local/bin/promtail-linux-amd64"
  register:    promtailbin

- name:        assert /usr/local/bin/promtail-linux-amd64
  assert:       
    that:
        - promtailbin.stat.exists
    quiet:      true
    fail_msg:   'please install promtail-linux-amd64(1)'
####################################################  symlinks 
- name:    symlink promtail
  file:    src='/usr/local/bin/promtail-linux-amd64'   dest='/usr/local/bin/promtail'   state=link  owner=root   force=yes
####################################################  config files 

- name:         config files
  synchronize:  src=etc/loki    dest="/etc/"    owner=root  copy_links=yes  delete='no'  owner=no  dirs=yes rsync_opts=--ignore-existing

- name:        systemd file
  copy:        src=etc/systemd/system/promtail.service     dest="/etc/systemd/system/"     owner=root
  when:        os_family == 'Linux'
####################################################  mkdir

- name:       reload  promtail
  when:       os_family == 'Linux' 
  systemd:    name="promtail"   daemon_reload="yes"  state=started  enabled=yes
