#################################################################################
- name:            prometheus repository
  when:      false
  blockinfile:
      insertbefore:     EOF
      path:             /etc/yum.repos.d/prometheus.repo
      owner:            root
      create:           yes
      block: |
            [prometheus]
            name=prometheus
            baseurl=https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
            repo_gpgcheck=1
            enabled=1
            gpgkey=https://packagecloud.io/prometheus-rpm/release/gpgkey
                   https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
            gpgcheck=1
            metadata_expire=300

#################################################################################


- name:     group prometheus
  group:    name=prometheus    #gid=1002

- name:     user prometheus
  user:     name=prometheus  shell="/bin/false"    createhome=no  group=prometheus  # password=sobxtSZ2VA78Q

- name:     directory /etc/prometheus
  file:     dest="/etc/prometheus"         state=directory      owner=prometheus  mode=755


#################################################################################
- name:      prometheus
  unarchive:
      src:   https://github.com/prometheus/prometheus/releases/download/v{{PROMETHEUS_VERSION}}/prometheus-{{PROMETHEUS_VERSION}}.linux-amd64.tar.gz 
      dest:         /tmp
      remote_src:   yes
      creates:      "/tmp/prometheus-{{ PROMETHEUS_VERSION}}.linux-amd64"

- copy:      
     src:          "/tmp/prometheus-{{ PROMETHEUS_VERSION}}.linux-amd64/prometheus"    
     dest:        "/usr/local/bin/prometheus-{{PROMETHEUS_VERSION}}"  
     remote_src:   yes
     force:        no
     mode:         755

- name:        link /usr/local/bin/prometheus
  file:  
     src:      "/usr/local/bin/prometheus-{{PROMETHEUS_VERSION}}"  
     dest:     /usr/local/bin/prometheus
     state:    link  
     owner:    root
     force:    yes

- copy:      
     src:          "/tmp/prometheus-{{ PROMETHEUS_VERSION}}.linux-amd64/promtool"    
     dest:        /usr/local/bin/
     remote_src:   yes
     force:        no
     mode:         755
#################################################################################
- name:      alertmanager
  unarchive:
      src:   https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:     /tmp/alertmanager-0.21.0.linux-amd64

- copy:      
     src:         "/tmp/alertmanager-0.21.0.linux-amd64/alertmanager"
     dest:        /usr/local/bin/alertmanager-0.21.0
     remote_src:   yes
     force:        no
     mode:         755

- name:        link /usr/local/bin/altermanager
  file:  
     src:      /usr/local/bin/alertmanager-0.21.0
     dest:     /usr/local/bin/alertmanager
     state:    link  
     owner:    root
     force:    yes

- copy:      
     src:         /tmp/alertmanager-0.21.0.linux-amd64/amtool 
     dest:        /usr/local/bin/
     remote_src:   yes
     force:        no
     mode:         755
#################################################################################
- name:      blackbox_exporter
  unarchive:
      src:   https://github.com/prometheus/blackbox_exporter/releases/download/v0.18.0/blackbox_exporter-0.18.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/blackbox_exporter-0.18.0.linux-amd64

- copy:      
     src:          /tmp/blackbox_exporter-0.18.0.linux-amd64/blackbox_exporter  
     dest:         /usr/local/bin/blackbox_exporter-0.18.0
     remote_src:   yes
     force:        no
     mode:         755

- name:        link /usr/local/bin/blackbox
  file:  
     src:      /usr/local/bin/blackbox_exporter-0.18.0
     dest:     /usr/local/bin/blackbox
     state:    link  
     owner:    root
     force:    yes
#################################################################################
- name:      node_exporter
  unarchive:
      src:   https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/node_exporter-1.0.1.linux-amd64

- copy:      
     src:          /tmp/node_exporter-1.0.1.linux-amd64/node_exporter
     dest:         /usr/local/bin/node_exporter-1.0.1
     remote_src:   yes
     force:        no
     mode:         755

- name:        link /usr/local/bin/node_explorter
  file:  
     src:      /usr/local/bin/node_exporter-1.0.1
     dest:     /usr/local/bin/node_exporter
     state:    link  
     owner:    root
     force:    yes
#################################################################################
- name:      pushgateway
  unarchive:
      src:   https://github.com/prometheus/pushgateway/releases/download/v1.3.0/pushgateway-1.3.0.linux-amd64.tar.gz
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/pushgateway-1.3.0.linux-amd64

- copy:      
     src:           /tmp/pushgateway-1.3.0.linux-amd64/pushgateway
     dest:          /usr/local/bin/pushgateway-1.3.0
     remote_src:    yes
     force:         no
     mode:         755

- name:        link /usr/local/bin/pushgateway
  file:  
     src:      /usr/local/bin/pushgateway-1.3.0
     dest:     /usr/local/bin/pushgateway
     state:    link  
     owner:    root
     force:    yes
#################################################################################
- name:      consul_exporter
  unarchive:
      src:   https://github.com/prometheus/consul_exporter/releases/download/v0.7.1/consul_exporter-0.7.1.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/consul_exporter-0.7.1.linux-amd64

- copy:      
     src:           /tmp/consul_exporter-0.7.1.linux-amd64/consul_exporter
     dest:          /usr/local/bin/consul_exporter-0.7.1
     remote_src:    yes
     force:         no
     mode:         755

- name:             link /usr/local/bin/consul_exporter
  file:  
     src:           /usr/local/bin/consul_exporter-0.7.1
     dest:          /usr/local/bin/consul_exporter
     state:         link  
     owner:         root
     force:         yes
#################################################################################
- name:      memcached_exporter
  unarchive:
      src:   https://github.com/prometheus/memcached_exporter/releases/download/v0.7.0/memcached_exporter-0.7.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/memcached_exporter-0.7.0.linux-amd64

- command:       cp -a /tmp/memcached_exporter-0.7.0.linux-amd64/memcached_exporter     "/usr/local/bin/"  
#################################################################################
- name:      statsd_exporter
  unarchive:
      src:   https://github.com/prometheus/statsd_exporter/releases/download/v0.18.0/statsd_exporter-0.18.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/statsd_exporter-0.18.0.linux-amd64

- copy:      
     src:            /tmp/statsd_exporter-0.18.0.linux-amd64/statsd_exporter
     dest:           /usr/local/bin/statsd_exporter-0.18.0
     remote_src:    yes
     force:         no
     mode:         755

- name:        link /usr/local/bin/statsd_exporter
  file:  
     src:      /usr/local/bin/statsd_exporter-0.18.0
     dest:     /usr/local/bin/statsd_exporter
     state:    link  
     owner:    root
     force:    yes
#################################################################################
- name:      graphite_exporter
  unarchive:
      src:   https://github.com/prometheus/graphite_exporter/releases/download/v0.9.0/graphite_exporter-0.9.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/graphite_exporter-0.9.0.linux-amd64

- command:       cp -a /tmp/graphite_exporter-0.9.0.linux-amd64/graphite_exporter     "/usr/local/bin/"  
#################################################################################
- name:      mysqld
  unarchive:
      src:   https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/mysqld_exporter-0.12.1.linux-amd64

- command:       cp -a /tmp/mysqld_exporter-0.12.1.linux-amd64/mysqld_exporter     "/usr/local/bin/"  
#################################################################################
- name:      haproxy_exporter
  unarchive:
      src:   https://github.com/prometheus/haproxy_exporter/releases/download/v0.11.0/haproxy_exporter-0.11.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/haproxy_exporter-0.11.0.linux-amd64

- command:       cp -a /tmp/haproxy_exporter-0.11.0.linux-amd64/haproxy_exporter     "/usr/local/bin/"  
#################################################################################
#
- name:  delete  dirs
  when:  false
  shell:  rm -rf /tmp/*linx-amd64



####################################################  /etc/prometheus   FILES
- name:        Files
  include:     prometheus/files.yml

- name:  chown -R /etc/prometheus
  shell:  chown -R prometheus:prometheus /etc/prometheus

- name:   overide default symlink from prometheus/files.yml
  file:    src='/etc/prometheus/tiny.yml'   dest='/etc/prometheus/prometheus.yml'   state=link  owner=prometheus   force=yes
 

####################################################   systemd for centos 
- name:        systemd for centos
  synchronize:  src="etc/systemd/centos/"  dest="/etc/systemd/system"   delete='no'  owner=no  dirs=yes rsync_opts=--ignore-existing
####################################################   firewall so others can reach prometheus
# firewall-cmd --add-port=9090/tcp --permanent
# firewall-cmd reload

####################################################   reload servers
- name:    systemd
  include: prometheus/systemd-RedHat.yml
