####################################################  packages
- name:          packages prometheus 
  apt:
     pkg:
                  - prometheus-blackbox-exporter 
                  - prometheus-postgres-exporter
                  - prometheus-pgbouncer-exporter
                  - prometheus-node-exporter
                  - prometheus-pushgateway 
                  - prometheus-apache-exporter
                  - pgbouncer
                  - prometheus-alertmanager
                  - prometheus 

####################################################  /etc/prometheus   FILES
- name:        Files
  include:     prometheus/files.yml

- name:    overide symlink  prometheus.yml, earlied defined in prometheus/files.yml
  file:    src='/etc/prometheus/dynamic_file_fed.yml'   dest='/etc/prometheus/prometheus.yml'   state=link  owner=root   force=yes

####################################################  systemd
- name:        systemd
  include:     prometheus/systemd-Debian.yml
