####################################################  packages

####################################################  /etc/prometheus   FILES
- name:        Files   /etc/prometheus/*
  synchronize:  src="etc/prometheus/"  dest="/etc/prometheus"    delete='no'  owner=no  dirs=yes #rsync_opts=--ignore-existing

####################################################  /etc/prometheus  TEMPLATES
#
- name:        Templates /etc/prometheus/*
  template:    src=etc/prometheus/{{ item }}      dest="/etc/prometheus/"     owner=root
  with_items:
       - tiny.yml
       - static.yml          
       - pg.yml          
       - static_read-pg.yml  
       - static_write-pg.yml
       - federate_server.yml
       - federate_client.yml
       - dynamic_file.yml    
       - dynamic_consul.yml  
       - simple_consul.yml   
       - simple_consul_fed.yml   
       - pg_both_fed.yml     
       - pg_both.yml           


####################################################  symlinks 
- name:    symlink  prometheus.yml
  file:    src='/etc/prometheus/pg_both_fed.yml'   dest='/etc/prometheus/prometheus.yml'   state=link  owner=root   force=yes

- name:    symlink  rules/memory_rules.yml
  file:    src="/etc/prometheus/rules/memory_{{ os_family }}.yml"   dest='/etc/prometheus/rules/memory.yml'   state=link  owner=root   force=yes

- name:    symlink  /etc/prometheus/makefile
  file:    src='/etc/prometheus/validate/makefile_Darwin'   dest='/etc/prometheus/makefile'   state=link  owner=root   force=yes

####################################################  /etc/default
####################################################  other exporters
- name:   grok_exporter
  when:   need_grok_exporter
  include:  grok_exporter.yml
####################################################  mkdir
- name:    mkdir  node_dat
  file:    dest='/var/lib/prometheus/node_dat'    state=directory  owner=root   force=yes

####################################################   reload servers

- name:       reload  prometheus exporters
  when:  false
  shell:       "/etc/init.d/prometheus-{{ item }}-exporter    force-reload"
  with_items:
      - postgres
      - node
        
# reload prometheus
