- name:     group prometheus
  group:    name=prometheus    #gid=1002

- name:     user prometheus
  user:     name=prometheus  shell="/bin/false"    createhome=no  group=prometheus  # password=sobxtSZ2VA78Q

- name:     directory /etc/prometheus
  file:     dest="/etc/prometheus"         state=directory      owner=prometheus  mode=755

- name:     directory /var/lib/prometheus/node-exporter/node_dat
  file:     dest="/var/lib/prometheus/node-exporter/node_dat"    state=directory      owner=prometheus  mode=755
  

#################################################################################
- name:      prometheus
  unarchive:
      src:   https://github.com/prometheus/prometheus/releases/download/v{{PROMETHEUS_VERSION}}/prometheus-{{PROMETHEUS_VERSION}}.linux-amd64.tar.gz 
      dest:         /tmp
      remote_src:   yes
      creates:      "/tmp/prometheus-{{ PROMETHEUS_VERSION}}.linux-amd64"

- command:       cp -a "/tmp/prometheus-{{ PROMETHEUS_VERSION}}.linux-amd64/prometheus"     "/usr/local/bin/"  
- command:       cp -a "/tmp/prometheus-{{ PROMETHEUS_VERSION}}.linux-amd64/promtool"       "/usr/local/bin/"  
#################################################################################
- name:      alertmanager
  unarchive:
      src:   https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:     /tmp/alertmanager-0.21.0.linux-amd64

- command:       cp -a "/tmp/alertmanager-0.21.0.linux-amd64/alertmanager"     "/usr/local/bin/"  
- command:       cp -a "/tmp/alertmanager-0.21.0.linux-amd64/amtool"           "/usr/local/bin/"  
#################################################################################
- name:      blackbox_exporter
  unarchive:
      src:   https://github.com/prometheus/blackbox_exporter/releases/download/v0.18.0/blackbox_exporter-0.18.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/blackbox_exporter-0.18.0.linux-amd64

- command:       cp -a "/tmp/blackbox_exporter-0.18.0.linux-amd64/blackbox_exporter"     "/usr/local/bin/"  
#################################################################################
- name:      node_exporter
  unarchive:
      src:   https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/node_exporter-1.0.1.linux-amd64

- command:       cp -a "/tmp/node_exporter-1.0.1.linux-amd64/node_exporter"     "/usr/local/bin/"  
#################################################################################
- name:      pushgateway
  unarchive:
      src:   https://github.com/prometheus/pushgateway/releases/download/v1.3.0/pushgateway-1.3.0.linux-amd64.tar.gz
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/pushgateway-1.3.0.linux-amd64

- command:       cp -a /tmp/pushgateway-1.3.0.linux-amd64/pushgateway     "/usr/local/bin/"  
#################################################################################
- name:      consul_exporter
  unarchive:
      src:   https://github.com/prometheus/consul_exporter/releases/download/v0.7.1/consul_exporter-0.7.1.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/consul_exporter-0.7.1.linux-amd64

- command:       cp -a /tmp/consul_exporter-0.7.1.linux-amd64/consul_exporter     "/usr/local/bin/"  
#################################################################################
- name:      memcached_exporter
  unarchive:
      src:   https://github.com/prometheus/memcached_exporter/releases/download/v0.7.0/memcached_exporter-0.7.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/memcached_exporter-0.7.0.linux-amd64

- command:       cp -a /tmp/memcached_exporter-0.7.0.linux-amd64/memcached_exporter     "/usr/local/bin/"  
#################################################################################
- name:      statsd_exporter
  unarchive:
      src:   https://github.com/prometheus/statsd_exporter/releases/download/v0.18.0/statsd_exporter-0.18.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/statsd_exporter-0.18.0.linux-amd64

- command:       cp -a /tmp/statsd_exporter-0.18.0.linux-amd64/statsd_exporter     "/usr/local/bin/"  
#################################################################################
- name:      graphite_exporter
  unarchive:
      src:   https://github.com/prometheus/graphite_exporter/releases/download/v0.9.0/graphite_exporter-0.9.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/graphite_exporter-0.9.0.linux-amd64

- command:       cp -a /tmp/graphite_exporter-0.9.0.linux-amd64/graphite_exporter     "/usr/local/bin/"  
#################################################################################
- name:      mysqld
  unarchive:
      src:   https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/mysqld_exporter-0.12.1.linux-amd64

- command:       cp -a /tmp/mysqld_exporter-0.12.1.linux-amd64/mysqld_exporter     "/usr/local/bin/"  
#################################################################################
- name:      haproxy_exporter
  unarchive:
      src:   https://github.com/prometheus/haproxy_exporter/releases/download/v0.11.0/haproxy_exporter-0.11.0.linux-amd64.tar.gz	
      dest:         /tmp
      remote_src:   yes
      creates:      /tmp/haproxy_exporter-0.11.0.linux-amd64

- command:       cp -a /tmp/haproxy_exporter-0.11.0.linux-amd64/haproxy_exporter     "/usr/local/bin/"  
#################################################################################
#
- name:  delete  dirs
  when:  false
  shell:  rm -rf /tmp/*linx-amd64

