

- include: pgbloat.yml

- include: prometheus-RedHat.yml
  when:    need_prometheus

- include: grafana-RedHat.yml
  when:    need_grafana

- include: loki-Linux.yml
  when:    need_loki

- include: promtail-Linux.yml
  when:    need_promtail

- include: pgspray-RedHat.yml
  when:    need_pgspray

- include: consul-RedHat.yml
  when:    need_consul

  #- include: grok_exporter-Linux.yml
  #when:    need_grok_exporter
