     - name:       populate  .ssh for root
       copy:       src="ssh_keys/root/.ssh"   dest="/root" directory_mode=0700   owner="root" 
       when:       os_family == "Linux"

     - name:       populate  .ssh for root 
       copy:       src="ssh_keys/root/.ssh"   dest="/root" directory_mode=0700   owner="root" group="wheel"
       when:       os_family == "FreeBSD"

     - name:       populate  .ssh for non-root users
       copy:       src="ssh_keys/{{item}}/.ssh"   dest="{{HOME}}/{{item}}"  directory_mode=0700   owner="{{item}}"  #group="{{item}}"
       with_items:
             - ioannis
             - postgres
             - vagrant
             - nagios


     - name:   perms   id_rsa
       file:   path="{{HOME}}/{{ item }}/.ssh/id_rsa"   owner="{{ item }}"   mode=600
       when:       os_family == "Linux"
       ignore_errors: yes
       with_items:
           - ioannis
           - postgres
           - vagrant
           - nagios

     - copy:    src="ssh_keys/root/.ssh"   dest="/root/.ssh"  directory_mode=0700   owner='root'
       when:    os_family != "Darwin"

     - file:   path="/root/.ssh/id_rsa"   owner='root'   mode=600
       when:    os_family != "Darwin"

     - copy:    src="ssh_keys/root/.ssh"   dest="/var/root/.ssh"  directory_mode=0700   owner='root'
       when:    os_family == "Darwin"

     - file:   path="/var/root/.ssh/id_rsa"   owner='root'   mode=600
       when:    os_family == "Darwin"

  
     - name: perm id_rsa.pub
       file: path="{{HOME}}/{{ item }}/.ssh/id_rsa.pub"  owner="{{ item }}" mode=644
       with_items:
           - ioannis
           - postgres
           - vagrant
           - nagios

     - name: perm root id_rsa.pub
       file: path="/root/.ssh/id_rsa.pub"    owner=root    mode=644 
       when:    os_family != "Darwin"

     - name: perm authorized_keys
       file: path="{{HOME}}/{{ item }}/.ssh/authorized_keys"  owner="{{ item }}" mode=644
       with_items:
           - ioannis
           - postgres
           - vagrant
           - nagios

     - name: perm root authorized_keys
       file: path="/root/.ssh/authorized_keys"    owner=root    mode=644 
       when:    os_family != "Darwin"
