{
 "title": "main_prom",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "LOGDIR", "query": "/dev/sda1,/dev/sda6" },
   { "name": "DATA", "query": "/dev/sda1,/dev/sda6" },
   { "name": "query_len", "query": "65,90,100,130,150" },
   { "name": "db", "query": "postgres,ts,timescaledb" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds"
    }
   ]
  },
  {
   "title": "db:     $db  (live)",
   "type": "table-old",
   "description": "current_setting()",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\nVALUES ('conflicts',  (SELECT conflicts FROM pg_stat_database WHERE datname = $db))\n       , ('temp_files', (SELECT temp_files FROM pg_stat_database WHERE datname = $db))\n      -- , ('numbackends', (SELECT numbackends FROM pg_stat_database WHERE datname = $db))\n      -- , ('temp_bytes', (SELECT temp_bytes FROM pg_stat_database WHERE datname = $db))\n      ,  ('deadlocks', (SELECT deadlocks FROM pg_stat_database WHERE datname = $db))\n      -- ('blk_read_time', (SELECT blk_read_time FROM pg_stat_database WHERE datname = $db))\n     ) i(metric,value)\n     \nunion\nSELECT  'months until AV_FREEZE_MAX_AGE'\n      , (diff/(7*24*60*60*xact/epoch)/4 ::int)::int    AS  \"weeks remain\"\nFROM (\n    SELECT  S.datname\n       , extract (epoch from (now()-pg_stat_get_db_stat_reset_time(datid)))  AS epoch\n       , xact_commit + xact_rollback                                         AS xact\n       , current_setting('autovacuum_freeze_max_age')::int  - age(datfrozenxid)       AS diff\n    FROM pg_stat_database S JOIN pg_database D  ON (S.datname = D.datname)\n        WHERE D.datname = $db \n)i\n\n"
    }
   ]
  },
  { "title": "connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Backends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string", "label": "num  backends" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ( pg_stat_database_numbackends)"
    }
   ]
  },
  {
   "title": "available",
   "type": "stat",
   "description": "connections available (live)",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pg_settings_max_connections)  - sum (pg_stat_database_numbackends)"
    }
   ]
  },
  {
   "title": "available ",
   "type": "graph",
   "description": "connections available",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "num  backends" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)"
    },
    { "expr": "pg_settings_max_connections\n" }
   ]
  },
  {
   "title": "refused",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string", "label": "num  backends" }
   ]
  },
  {
   "title": "connections for \"$db\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "rate for \"$db\"",
   "type": "graph",
   "description": "Connection rate for db=$db",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_activity_count{datname=\"$db\"}[4m]))",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "response time",
     "type": "graph",
     "description": "response time : samples + sma",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT $__time(ts), 1000* response AS response\n        -- , 1000* avg(response) OVER(ORDER BY ts ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) AS sma\n\nFROM response_time\nWHERE \n $__timeFilter(ts) \n AND host = $host\n AND cluster = $cluster\n"
      }
     ]
    },
    {
     "title": "95th percentile",
     "type": "singlestat",
     "description": "response time",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 21 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": " SELECT  1000*percentile_disc( .95) WITHIN GROUP (ORDER BY response)\nFROM\n    (SELECT response, ts\n    FROM response_time\n    WHERE host = $host\n       AND cluster = $cluster\n       AND  $__timeFilter(ts)\n       AND  ts > now() - '65 minutes'::interval\n       AND  md5 = (SELECT last(md5,ts) FROM response_time)\n   ) i\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "db  sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "db sizes",
     "type": "grafana-piechart-panel",
     "description": "db sizes in cluster 'main'",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_database_size_bytes\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    },
    {
     "title": "db size",
     "type": "graph",
     "description": "db sizes in cluster 'main'",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "size" }
     ],
     "targets": [
      {
       "expr": "pg_database_size_bytes\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    },
    {
     "title": "available   ",
     "type": "graph",
     "description": "disk left  for partition  $DATA",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "size" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{device=\"$DATA\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "$DATA",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{device=\"$DATA\"} -      node_filesystem_avail_bytes{device=\"$DATA\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "wal ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "xlog",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "num   wals" }
     ],
     "targets": [
      { "expr": "pg_xlog_total", "legendFormat": "wal" }
     ]
    },
    {
     "title": "clog",
     "type": "graph",
     "description": "pg_clog  (or pg_xact)   size for cluster",
     "gridPos": { "h": 7, "w": 8, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "size" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "log dir (text & csv)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "pg_logdir_size", "legendFormat": "logsizes " }
     ]
    },
    {
     "title": "available   ",
     "type": "graph",
     "description": "disk left  for partition  $LOGDIR",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "size" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{device=\"$LOGDIR\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "$DATA",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{device=\"$LOGDIR\"} -      node_filesystem_avail_bytes{device=\"$LOGDIR\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "xact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "xact  per db",
     "type": "graph",
     "description": "facts for each database in the cluster",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "transactions" }
     ],
     "targets": [
      {
       "expr": "rate (pg_stat_database_xact_commit[5m])",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "tps",
     "type": "stat",
     "description": "cummulative  tps  for all databases",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(pg_stat_database_xact_commit[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "xact  for \"$db\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "xact  for \"$db\"",
     "type": "graph",
     "description": "commited xact for db=$db",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "transactions" }
     ],
     "targets": [
      {
       "expr": "rate (pg_stat_database_xact_commit{datname=\"$db\"}[5m])",
       "legendFormat": "$db"
      }
     ]
    },
    {
     "title": "tps for \"$db\"",
     "type": "stat",
     "description": "tps  for db=$db",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(pg_stat_database_xact_commit{datname=\"$db\"}[5m]))",
       "legendFormat": "$db"
      }
     ]
    },
    {
     "title": "% rollbacks for \"$db\"",
     "type": "stat",
     "description": "% xact that rolled back at db=$db",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100*(pg_stat_database_xact_rollback{datname=\"$db\"})/ \n(pg_stat_database_xact_commit{datname=\"$db\"})",
       "legendFormat": "$db"
      }
     ]
    }
   ]
  },
  {
   "title": "bgwriter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "times",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none", "label": "write   time     (ms)" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time[3m])"
      }
     ]
    },
    {
     "title": "buffers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "none", "label": "num buffers" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend[3m])",
       "legendFormat": "backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean[3m])",
       "legendFormat": "clean"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint[3m])",
       "legendFormat": "checkpoint"
      }
     ]
    },
    {
     "title": "requested",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "none", "label": "count" }
     ],
     "targets": [
      {
       "expr": "pg_stat_bgwriter_checkpoints_req",
       "legendFormat": "req"
      },
      {
       "expr": "pg_stat_bgwriter_checkpoints_timed",
       "legendFormat": "timed"
      }
     ]
    }
   ]
  },
  {
   "title": "bgwriter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cleaned By",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_stat_bgwriter_buffers_backend",
       "legendFormat": "backend"
      },
      {
       "expr": "pg_stat_bgwriter_buffers_checkpoint",
       "legendFormat": "checkpoint"
      },
      { "expr": "pg_stat_bgwriter_buffers_clean", "legendFormat": "clean" }
     ]
    },
    {
     "title": "Cleaned By",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 6, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "pg_stat_bgwriter_buffers_backend_fsync",
       "legendFormat": "fsync"
      },
      {
       "expr": "pg_stat_bgwriter_maxwritten_clean",
       "legendFormat": "maxwritten_clean"
      }
     ]
    },
    {
     "title": "tps",
     "type": "stat",
     "description": "cummulative  tps  for all databases",
     "gridPos": { "h": 7, "w": 8, "x": 13, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_bgwriter_buffers_backend_fsync)",
       "legendFormat": "buffers_backend_fsync"
      },
      {
       "expr": "sum(pg_stat_bgwriter_maxwritten_clean)",
       "legendFormat": "maxwritten_clean"
      }
     ]
    }
   ]
  },
  {
   "title": "stat statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "stat_statements",
     "type": "yesoreyeram-boomtable-panel",
     "description": "top-3   costliest stat_statments",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 29 },
     "targets": [
      { "expr": "   ", "legendFormat": "{{instance}}|cpu" }
     ]
    }
   ]
  },
  {
   "title": "config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "checkpoint  -- $ds  (live)",
     "type": "table-old",
     "description": "current_setting()",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT name, setting,unit\nFROM pg_settings\nWHERE name IN ('checkpoint_timeout', 'bgwriter_lru_maxpages', 'bgwriter_lru_multiplier',\n               'checkpoint_timeout', 'log_checkpoints____','checkpoint_flush_after')\nORDER BY name\n\n \n"
      }
     ]
    },
    {
     "title": "seepdup  -- $ds   (live)",
     "type": "table-old",
     "description": "current_setting()",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT name, setting\nFROM pg_settings\nWHERE name IN  (\n      'effective_io_concurrency' , \n     'fsync'  ,                  \n     'max_replication_slots' ,    \n     'synchronous_commit' ,       \n     'wal_compression',          \n     'wal_level')\nORDER BY name\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "replication slots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "replication lag",
     "type": "graph",
     "description": "From pg_replication",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_replication_lag)",
       "rawSql": "SELECT\n now() AS time\n, application_name AS metric\n, pg_xlog_location_diff( pg_current_xlog_location(), replay_location)\nFROM pg_stat_replication\n\n\n"
      }
     ]
    },
    {
     "title": "Slots  Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_settings_max_replication_slots      -   pg_replication_slots_available",
       "legendFormat": "used"
      },
      {
       "expr": "pg_settings_max_replication_slots",
       "legendFormat": "max available"
      }
     ]
    },
    {
     "title": "Slots  Available",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "pg_replication_slots_available" }
     ]
    }
   ]
  }
 ]
}