{
 "title": "pg Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(pg_up,hostname)\n\n"
   },
   { "name": "cluster", "query": "label_values(pg_up,cluster) \n" },
   {
    "name": "db",
    "query": "label_values(pg_locks_count{hostname=\"$host\"},datname)"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "port",
    "query": "label_values(pg_up{hostname=\"$host\"},pg_port)"
   },
   { "name": "query_len", "query": "65,90,100,130,150" },
   {
    "name": "LOGDIR",
    "query": "label_values(node_filesystem_avail_bytes{mountpoint=\"/\",hostname=\"$host\"},device)"
   },
   {
    "name": "DATA",
    "query": "label_values(node_filesystem_avail_bytes{mountpoint=\"/\",hostname=\"$host\"},device)"
   },
   {
    "name": "role",
    "query": "ioannis,postgres,readonly,prometheus"
   },
   {
    "name": "services",
    "query": "label_values(probe_success,service)\n"
   },
   {
    "name": "delta",
    "query": "1m,2m,3m,5m,10m,30m,1h,4h,6h,1d"
   },
   {
    "name": "HOSTS",
    "query": "label_values(pg_up,hostname)\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "pg_settings_log_checkpoints{cluster=\"$cluster\"}",
       "legendFormat": "log_checkpoints"
      },
      {
       "expr": "pg_settings_vacuum_freeze_table_age{cluster=\"$cluster\"}",
       "legendFormat": "vacuum_freeze_table_age"
      }
     ]
    }
   ]
  },
  {
   "title": "bar graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "db sizes",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_database_size_bytes{hostname=\"$host\",cluster=\"$cluster\",datname!~\"^template.*\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 10, "y": 9 },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "musti-stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "blackbox",
     "type": "michaeldmoore-multistat-panel",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "probe_success{hostname=\"$host\"}",
       "legendFormat": "{{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "boom table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "pg_settings_ssl{hostname=\"$host\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(node_cpu_seconds_total{hostname=\"$host\",mode=\"idle\"})",
       "legendFormat": "{{instance}}|CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "poly",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "pg_up{hostname=\"$host\"}",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "pg_up{hostname=\"$host\"}",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(pg_postmaster_start_time_seconds{hostname=\"$host\",cluster=\"$cluster\"},\"hostport\", ':', \"host_ip\", \"pg_port\")/1000"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": " 100-100*avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}|CPU"
    },
    {
     "expr": " 100-100*node_filesystem_avail_bytes{hostname=\"qft\",mountpoint=\"/home\"}/node_filesystem_size_bytes{hostname=\"qft\"}",
     "legendFormat": "{{instance}}|DiskUsed"
    }
   ]
  },
  {
   "title": "blackbox tcp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "pgspray",
     "type": "vonage-status-panel",
     "description": "pgspray via systemd(5)",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "systemd",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\", name=\"pgspray.service\"}",
       "legendFormat": "systemd",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "pgspray ",
     "type": "vonage-status-panel",
     "description": "psgi via plack(5)",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "plack",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"plack\"}",
       "legendFormat": "plack",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "loki",
     "type": "vonage-status-panel",
     "description": "psgi via plack(5)",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "loki",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"loki\"}",
       "legendFormat": "loki",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "fluent-bit",
     "type": "vonage-status-panel",
     "description": "psgi via plack(5)",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "fluent-bit",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"fluent-bit\"}",
       "legendFormat": "fluent-bit",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "blackbox",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "blackbox",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"blackbox-exporter\"}",
       "legendFormat": "blackbox",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "pg server $cluster",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "pg server",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"pg server $cluster\"}",
       "legendFormat": "pg server",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "pgexporter-$cluster",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "pgexporter",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"postgres-exporter-$cluster\"}",
       "legendFormat": "pgexporter",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "grok-exporter-$cluster",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "grok",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"grok-exporter-$cluster\"}",
       "legendFormat": "grok",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "postfix",
     "type": "vonage-status-panel",
     "description": "pgspray via systemd(5)",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "systemd",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\", name=\"postfix.service\"}",
       "legendFormat": "systemd",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "apache2",
     "type": "vonage-status-panel",
     "description": "pgspray via systemd(5)",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "systemd",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\", name=\"apache2.service\"}",
       "legendFormat": "systemd",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "blackbox",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "blackbox",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"blackbox-exporter\"}",
       "legendFormat": "blackbox",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "consul http",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "consul http",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"consul http\"}",
       "legendFormat": "consul http",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "prometheus",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "prometheus",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"prometheus\"}",
       "legendFormat": "prometheus",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "promtail",
     "type": "vonage-status-panel",
     "description": "psgi via plack(5)",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "promtail",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"promtail\"}",
       "legendFormat": "promtail",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    },
    {
     "title": "pushgateway",
     "type": "vonage-status-panel",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
     "targets": [
      {
       "aggregation": "Last",
       "alias": "pushgateway",
       "crit": "0",
       "decimals": 2,
       "displayAliasType": "Always",
       "displayType": "Regular",
       "displayValueWithAlias": "When Alias Displayed",
       "expr": "probe_success{hostname=\"$host\",service=\"pushgateway-exporter\"}",
       "legendFormat": "pushgateway",
       "units": "none",
       "valueHandler": "String Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "blackbox",
     "type": "michaeldmoore-multistat-panel",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "probe_success{hostname=\"$host\"}",
       "legendFormat": "{{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "heatmap",
     "type": "heatmap",
     "description": "response time : samples + sma",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(pgspray_bucket{hostname=\"$host\",cluster=\"$cluster\"}[$delta])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "95th",
     "type": "stat",
     "description": "as reported by pgspray summary",
     "gridPos": { "h": 5, "w": 3, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 160 }
     ]
    },
    {
     "title": " 95th ",
     "type": "graph",
     "description": "response time from postres server. Calculation is based on histogram_quantile() .",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(increase(pgspray_bucket{hostname=\"$host\",cluster=\"$cluster\"}[$delta])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "quantile",
     "type": "graph",
     "description": "response time",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pgspray_response{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "{{quantile}}",
       "rawSql": " SELECT  1000*percentile_disc( .95) WITHIN GROUP (ORDER BY response)\nFROM\n    (SELECT response, ts\n    FROM response_time\n    WHERE host = $host\n       AND cluster = $cluster\n       AND  $__timeFilter(ts)\n       AND  ts > now() - '65 minutes'::interval\n       AND  md5 = (SELECT last(md5,ts) FROM response_time)\n   ) i\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backends",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "yaxes": [
      { "format": "string", "label": "num  backends" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) ( pg_stat_database_numbackends{hostname=\"$host\",cluster=\"$cluster\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "available",
     "type": "stat",
     "description": "connections available (live)",
     "gridPos": { "h": 5, "w": 4, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (pg_settings_max_connections{hostname=\"$host\",cluster=\"$cluster\"})  - sum (pg_stat_database_numbackends{hostname=\"$host\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "sturation",
     "type": "graph",
     "description": "connections available",
     "gridPos": { "h": 5, "w": 7, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "num  backends" }
     ],
     "targets": [
      {
       "expr": "sum( pg_stat_database_numbackends{hostname=~\"$host\",cluster=~\"$cluster\"})",
       "legendFormat": "backends",
       "requestId": "Q-7d362401-fd37-4753-b46e-ad5b57750d43-0Q-8d3076af-7609-4da7-a17d-4f23ac78e867-1A"
      },
      {
       "expr": "pg_settings_max_connections{hostname=~\"$host\",cluster=~\"$cluster\"}\n",
       "legendFormat": "max",
       "requestId": "Q-7d362401-fd37-4753-b46e-ad5b57750d43-0Q-8d3076af-7609-4da7-a17d-4f23ac78e867-1B"
      }
     ]
    },
    {
     "title": "refused",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 17, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "yaxes": [
      { "format": "string", "label": "num  backends" }
     ]
    }
   ]
  },
  {
   "title": "connection ERROR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "passwd failures, [$delta]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "yaxes": [
      { "format": "string" }
     ],
     "targets": [
      {
       "expr": "increase(pglog_passwd_failed{hostname=\"$host\",cluster=\"$cluster\"}[$delta])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "FATAL passwd ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 5, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_over_time({job=\"pglogs\"}|= \"FATAL\" [4m])"
      },
      {
       "expr": "count_over_time({job=\"pglogs\"}|= \"FATAL\" |= \"password\" [4m])"
      }
     ]
    },
    {
     "title": "FATAL passwd ",
     "type": "logs",
     "gridPos": { "h": 6, "w": 12, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "{job=\"pglogs\",hostname=\"$host\"} |=  \"FATAL\" |= \"password authen\""
      }
     ]
    }
   ]
  },
  {
   "title": "connections for \"$db\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$db\"  --  avg over [$delta]",
     "type": "graph",
     "description": "Connection rate for db=$db",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(pg_stat_activity_count{hostname=\"$host\",datname=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "c"
      }
     ]
    },
    {
     "title": "available for \"$db\"",
     "type": "stat",
     "description": "connections available (live)",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (pg_settings_max_connections{hostname=\"$host\",cluster=\"$cluster\"})  - sum (pg_stat_database_numbackends{hostname=\"$host\",datname=\"$db\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "error types",
     "type": "stat",
     "description": "cummulative  tps  for all databases",
     "gridPos": { "h": 7, "w": 8, "x": 10, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(pglog_error{hostname=\"$host\",cluster=\"$cluster\",datname=\"$db\"})",
       "legendFormat": "FATAL"
      },
      {
       "expr": "sum(pglog_error{hostname=\"$host\",cluster=\"$cluster\",datname=\"$db\"})",
       "legendFormat": "ERROR"
      }
     ]
    },
    {
     "title": "syntax  for \"$db\"",
     "type": "graph",
     "description": " rate  syntax errors for db=$db",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(pglog_error_syntax{hostname=\"$host\",datname=\"$db\"}[$delta])",
       "legendFormat": "c"
      }
     ]
    }
   ]
  },
  {
   "title": "connection  .log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "pglogs",
     "type": "logs",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{job=\"pglogs\",hostname=\"$host\"}"
      }
     ]
    },
    {
     "title": "auth ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "yaxes": [
      { "format": "string" }
     ],
     "targets": [
      {
       "expr": "sum(pglog_conn_ssl_authorized{hostname=$host\"})",
       "legendFormat": "ssl"
      },
      {
       "expr": "sum(pglog_conn_nossl{hostname=\"$host\"})",
       "legendFormat": "no _ssl"
      }
     ]
    }
   ]
  },
  {
   "title": "activity, for \"$db\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "user activity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (user) (pglog_error{hostname=\"$host\",cluster=\"$cluster\",datname=\"$db\"})",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "user activity [5m]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (user) (increase(pglog_error{hostname=\"$host\",cluster=\"$cluster\",datname=\"$db\"}[$delta]))",
       "legendFormat": "{{ user }}"
      }
     ]
    }
   ]
  },
  {
   "title": "errors, for \"$db\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "errors",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (severity) (pglog_error{hostname=\"$host\",cluster=\"$cluster\",datname=\"$db\",severity!=\"LOG\"})",
       "legendFormat": "{{ severity }}"
      }
     ]
    },
    {
     "title": "errors, [$delta]",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (severity) (increase(pglog_error{hostname=\"$host\",cluster=\"$cluster\",datname=\"$db\", severity!=\"LOG\"}[$delta]))",
       "legendFormat": "{{ severity }}"
      }
     ]
    }
   ]
  },
  {
   "title": "db  sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "db sizes",
     "type": "grafana-piechart-panel",
     "description": "db sizes in cluster 'main'",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_database_size_bytes{hostname=\"$host\",cluster=\"$cluster\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    },
    {
     "title": "db size",
     "type": "graph",
     "description": "db sizes in cluster 'main'",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "size" }
     ],
     "targets": [
      {
       "expr": "pg_database_size_bytes{hostname=\"$host\",cluster=\"$cluster\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    },
    {
     "title": "available   ",
     "type": "graph",
     "description": "disk left  for partition  $DATA",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "size" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{device=\"$DATA\",hostname=\"qft\",cluster=\"$cluster\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "$DATA",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{device=\"$DATA\", hostname=\"qft\"} -      node_filesystem_avail_bytes{device=\"$DATA\", hostname=\"qft\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "wal ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "xlog",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "num   wals" }
     ],
     "targets": [
      {
       "expr": "pg_xlog_total{hostname=\"$host\",cluster=\"$cluster'}",
       "legendFormat": "wal"
      }
     ]
    },
    {
     "title": "clog",
     "type": "graph",
     "description": "pg_clog  (or pg_xact)   size for cluster",
     "gridPos": { "h": 7, "w": 8, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "bytes", "label": "size" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "log dir (text & csv)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pg_logdir_sum{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "logsizes "
      }
     ]
    },
    {
     "title": "available",
     "type": "stat",
     "description": "connections available (live)",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "pg_logdir_sum{hostname=\"$host\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "available   ",
     "type": "graph",
     "description": "disk left  for partition  $LOGDIR",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "size" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{hostname=\"$host\",device=\"$LOGDIR\",cluster=\"$cluster\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "$DATA",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{hostname=\"$host\",device=\"$LOGDIR\"} -      node_filesystem_avail_bytes{hostname=\"$host\",device=\"$LOGDIR\"}\n",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "measurement": "postgresql_value",
       "rawSql": "SELECT\n  $__time(ts)\n  , datname AS metric\n  ,size     AS lessons \nFROM\n  scale.db_size\nWHERE\n  $__timeFilter(ts)\n  AND cluster = $cluster \n  AND host = $host\n -- And ts > now() - '20 minutes'::interval \n  ",
       "tags": [
        { "key": "instance", "operator": "=", "value": "db_sizes" },
        { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bench" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "xact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "xact  per db",
     "type": "graph",
     "description": "facts for each database in the cluster",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "transactions" }
     ],
     "targets": [
      {
       "expr": "rate (pg_stat_database_xact_commit{hostname=\"$host\",cluster=\"$cluster\"}[$delta])",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "tps",
     "type": "stat",
     "description": "cummulative  tps  for all databases",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_database_xact_commit{hostname=\"$host\"}[$delta]))"
      }
     ]
    }
   ]
  },
  {
   "title": "xact  for \"$db\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "xact  for \"$db\"",
     "type": "graph",
     "description": "commited xact for db=$db",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short", "label": "transactions" }
     ],
     "targets": [
      {
       "expr": "rate (pg_stat_database_xact_commit{hostname=\"$host\",datname=\"$db\",cluster=\"$cluster\"}[5m])",
       "legendFormat": "$db"
      }
     ]
    },
    {
     "title": "tps for \"$db\"",
     "type": "stat",
     "description": "tps  for db=$db",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(pg_stat_database_xact_commit{hostname=\"$host\",datname=\"$db\",cluster=\"$cluster\"}[$delta))",
       "legendFormat": "$db"
      }
     ]
    },
    {
     "title": "% rollbacks for \"$db\"",
     "type": "stat",
     "description": "% xact that rolled back at db=$db",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100*(pg_stat_database_xact_rollback{hostname=\"$host\",datname=\"$db\",cluster=\"$cluster\"})/ \n(pg_stat_database_xact_commit{hostname=\"$host\",datname=\"$db\",cluster=\"$cluster\"})",
       "legendFormat": "$db"
      }
     ]
    }
   ]
  },
  {
   "title": "bgwriter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "times",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "write   time     (ms)" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{hostname=\"$host\",cluster=\"$cluster\"}[$delta])"
      }
     ]
    },
    {
     "title": "buffers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "num buffers" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend{hostname=\"$host\",cluster=\"$cluster\"}[$delta])",
       "legendFormat": "backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean{hostname=\"$host\"}[3m])",
       "legendFormat": "clean"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{hostname=\"$host\"}[3m])",
       "legendFormat": "checkpoint"
      }
     ]
    },
    {
     "title": "requested",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "count" }
     ],
     "targets": [
      {
       "expr": "pg_stat_bgwriter_checkpoints_req{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "req"
      },
      {
       "expr": "pg_stat_bgwriter_checkpoints_timed",
       "legendFormat": "timed"
      }
     ]
    }
   ]
  },
  {
   "title": "bgwriter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cleaned By",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_stat_bgwriter_buffers_backend{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "backend"
      },
      {
       "expr": "pg_stat_bgwriter_buffers_checkpoint{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "checkpoint"
      },
      {
       "expr": "pg_stat_bgwriter_buffers_clean{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "clean"
      }
     ]
    },
    {
     "title": "Cleaned By",
     "type": "table",
     "gridPos": { "h": 5, "w": 10, "x": 6, "y": 40 },
     "targets": [
      {
       "expr": "pg_stat_bgwriter_buffers_backend_fsync{hostname=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "fsync"
      }
     ]
    },
    {
     "title": "tps",
     "type": "stat",
     "description": "cummulative  tps  for all databases",
     "gridPos": { "h": 7, "w": 7, "x": 16, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_bgwriter_buffers_backend_fsync{hostname=\"$host\",cluster=\"$cluster\"})",
       "legendFormat": "buffers_backend_fsync"
      },
      {
       "expr": "sum(pg_stat_bgwriter_maxwritten_clean{hostname=\"$host\"})",
       "legendFormat": "maxwritten_clean"
      }
     ]
    }
   ]
  },
  {
   "title": "stat statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "stat_statements",
     "type": "yesoreyeram-boomtable-panel",
     "description": "top-3   costliest stat_statments",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 30 },
     "targets": [
      { "expr": "   ", "legendFormat": "{{instance}}|cpu" }
     ]
    }
   ]
  },
  {
   "title": "config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "checkpoint  -- $ds  (live)",
     "type": "table-old",
     "description": "current_setting()",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT name, setting,unit\nFROM pg_settings\nWHERE name IN ('checkpoint_timeout', 'bgwriter_lru_maxpages', 'bgwriter_lru_multiplier',\n               'checkpoint_timeout', 'log_checkpoints____','checkpoint_flush_after')\nORDER BY name\n\n \n"
      }
     ]
    },
    {
     "title": "seepdup  -- $ds   (live)",
     "type": "table-old",
     "description": "current_setting()",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT name, setting\nFROM pg_settings\nWHERE name IN  (\n      'effective_io_concurrency' , \n     'fsync'  ,                  \n     'max_replication_slots' ,    \n     'synchronous_commit' ,       \n     'wal_compression',          \n     'wal_level')\nORDER BY name\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "replication slots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "replication lag",
     "type": "graph",
     "description": "From pg_replication",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_replication_lag{host=\"$host\",cluster=\"$cluster\"})",
       "rawSql": "SELECT\n now() AS time\n, application_name AS metric\n, pg_xlog_location_diff( pg_current_xlog_location(), replay_location)\nFROM pg_stat_replication\n\n\n"
      }
     ]
    },
    {
     "title": "Slots  Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_settings_max_replication_slots{host=\"$host\",cluster=\"$cluster\"}      -   pg_replication_slots_available{host=\"$host\",cluster=\"$cluster\"}",
       "legendFormat": "used"
      },
      {
       "expr": "pg_settings_max_replication_slots",
       "legendFormat": "max available"
      }
     ]
    },
    {
     "title": "Slots  Available",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_replication_slots_available{host=\"$host\",cluster=\"$cluster\"}"
      }
     ]
    }
   ]
  }
 ]
}