{
 "title": "services",
 "tags": [ "db" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(pg_up,hostname)\n\n"
   },
   { "name": "cluster", "query": "label_values(pg_up,cluster) \n" },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "port",
    "query": "label_values(pg_up{hostname=\"$host\"},pg_port)"
   },
   {
    "name": "services",
    "query": "label_values(probe_success,service)\n"
   },
   {
    "name": "delta",
    "query": "1m,2m,3m,5m,10m,30m,1h,4h,6h,1d"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(pg_postmaster_start_time_seconds{hostname=\"$host\",cluster=\"$cluster\"},\"hostport\", ':', \"host_ip\", \"pg_port\")/1000"
    }
   ]
  },
  { "title": "blackbox  tcp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "probe_success{hostname=\"$host\",service=~\".*$cluster.*\"}",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "probe_success{hostname=\"$host\",service=\"promtail\"}",
     "legendFormat": "promtail"
    },
    {
     "expr": "probe_success{hostname=\"$host\",service=\"pgspray\"}",
     "legendFormat": "pgspray"
    },
    {
     "expr": "probe_success{hostname=\"$host\",service=\"loki\"}",
     "legendFormat": "loki"
    },
    {
     "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\",name=\"pgspray.service\"}",
     "legendFormat": "pgspray"
    }
   ]
  },
  { "title": "blackbox tcp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "pgspray",
   "type": "vonage-status-panel",
   "description": "pgspray via systemd(5)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "systemd",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\", name=\"pgspray.service\"}",
     "legendFormat": "systemd",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "pgspray ",
   "type": "vonage-status-panel",
   "description": "psgi via plack(5)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "plack",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"plack\"}",
     "legendFormat": "plack",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "loki",
   "type": "vonage-status-panel",
   "description": "psgi via plack(5)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "loki",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"loki\"}",
     "legendFormat": "loki",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "fluent-bit",
   "type": "vonage-status-panel",
   "description": "psgi via plack(5)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "fluent-bit",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"fluent-bit\"}",
     "legendFormat": "fluent-bit",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "blackbox",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "blackbox",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"blackbox-exporter\"}",
     "legendFormat": "blackbox",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "pg server $cluster",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "pg server",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"pg server $cluster\"}",
     "legendFormat": "pg server",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "pgexporter-$cluster",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "pgexporter",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"postgres-exporter-$cluster\"}",
     "legendFormat": "pgexporter",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "grok-exporter-$cluster",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "grok",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"grok-exporter-$cluster\"}",
     "legendFormat": "grok",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "postfix",
   "type": "vonage-status-panel",
   "description": "pgspray via systemd(5)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "systemd",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\", name=\"postfix.service\"}",
     "legendFormat": "systemd",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "apache2",
   "type": "vonage-status-panel",
   "description": "pgspray via systemd(5)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "systemd",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "node_systemd_unit_state{hostname=\"$host\",state=\"active\", name=\"apache2.service\"}",
     "legendFormat": "systemd",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "blackbox",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "blackbox",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"blackbox-exporter\"}",
     "legendFormat": "blackbox",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "consul http",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "consul http",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"consul http\"}",
     "legendFormat": "consul http",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "prometheus",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "prometheus",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"prometheus\"}",
     "legendFormat": "prometheus",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "promtail",
   "type": "vonage-status-panel",
   "description": "psgi via plack(5)",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "promtail",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"promtail\"}",
     "legendFormat": "promtail",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "pushgateway",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "pushgateway",
     "crit": "0",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "probe_success{hostname=\"$host\",service=\"pushgateway-exporter\"}",
     "legendFormat": "pushgateway",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  { "title": "services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "blackbox",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "probe_success{hostname=\"$host\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}