global:
    #scrape_interval:      60s
  scrape_interval:      15s
  scrape_timeout:       10s 
  evaluation_interval:  3m
  # sample_limit:       10000

  # Labels when communicating with  external systems (federation, remote storage, Alertmanager).
  external_labels:
      server_ip: '{{ ansible_all_ipv4_addresses.0 }}'
      hostname : '{{ ansible_hostname }}'

#alerting:
#rule_files:
scrape_configs:

  - job_name: federate
    honor_labels:  true
    metrics_path:  '/federate' 

  - job_name: prometheus
    static_configs:
       - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
        labels:
