#Conuration documentation: https://prometheus.io/docs/operating/configuration
 
global:
  scrape_interval:      {{ scrape_interval     | default( '1m'  )  }}
  scrape_timeout:       {{ scrape_timeout      | default( '10s' )  }} 
  evaluation_interval:  {{ evaluation_interval | default( '1m'  )  }}
  # sample_limit:       {{ sample_limit        | default( '10000' )  }}

  # Labels when communicating with  external systems (federation, remote storage, Alertmanager).
  external_labels:
      host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
      hostname:  '{{ ansible_hostname }}'

rule_files:
   - "rules/memory.yml"
    #- "/etc/prometheus/alerts/first_alert.yml"
 
scrape_configs:

  - job_name: grok
    honor_labels: true
    static_configs:
        - targets: ['{{ ansible_hostname }}:9144'] 

  - job_name: postgres
    honor_labels: true
    static_configs:
        - targets: ['{{ ansible_hostname }}:9187'] 
          labels:
              host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
              hostname:  '{{ ansible_hostname }}'
              pg_port:   '5432'
    metric_relabel_configs:
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_[^nps].*'
     #    action: drop
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_.*t?'
     #    action: drop

        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop



  - job_name: node
    scrape_interval:  10s
    static_configs:
      - targets: ['localhost:9100']
        labels:
             host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
             hostname:  '{{ ansible_hostname }}'

# - job_name: postgres_5433
#   honor_labels: true
#   static_configs:
#       - targets: ['{{ ansible_hostname }}:9387'] 
#         labels:
#             host_ip:    '{{ ansible_all_ipv4_addresses.0 }}'
#             hostname : '{{ ansible_hostname }}'
#             pg_port: '5433'
#   metric_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'pg_settings_s[ysqtu].*'
#         action: drop
#       - source_labels: [datname]
#         regex: '^template[012]'
#         action: drop

# - job_name: 'pgbounce'
#   honor_labels: true
#   static_configs:
#       - targets: ['{{ ansible_hostname }}:9911'] 

#remote_write:
#       - url: http://localhost:9201/write
