#Conuration documentation: https://prometheus.io/docs/operating/configuration
 
global:
  scrape_interval:      {{ scrape_interval     | default( '1m'  )  }}
  scrape_timeout:       {{ scrape_timeout      | default( '10s' )  }} 
  evaluation_interval:  {{ evaluation_interval | default( '1m'  )  }}
  # sample_limit:       {{ sample_limit        | default( '10000' )  }}

  # Labels when communicating with  external systems (federation, remote storage, Alertmanager).
  external_labels:
      host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
      hostname:  '{{ ansible_hostname }}'

rule_files:
   - "rules/memory.yml"
    #- "/etc/prometheus/alerts/first_alert.yml"
 
scrape_configs:

  - job_name: blackbox
    metrics_path: /probe
    params:
       module: ['tcp_connect']
       #module: ['http_2xx']
    static_configs:
    - targets:
         - 127.0.0.1:9100  # node
         - 127.0.0.1:9144 # grok
         - 127.0.0.1:9145  # greok karat
         - 127.0.0.1:9187  # postgres 
         - 127.0.0.1:9188  # postgres karat
         - 127.0.0.1:5000  # pgspray
         - 127.0.0.1:2180  # consul
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: '{{ ansible_all_ipv4_addresses.0 }}':9115 # The blackbox exporter.
      # replacement: 127.0.0.1:9115 # The blackbox exporter.


  - job_name: grok
    honor_labels: true
    static_configs:
        - targets: ['{{ ansible_hostname }}:9144'] 

  - job_name: grok_karat
    honor_labels: true
    static_configs:
        - targets: ['{{ ansible_hostname }}:9145'] 

  - job_name: postgres
    honor_labels: true
    static_configs:
        - targets: ['{{ ansible_hostname }}:9187'] 
          labels:
              host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
              hostname:  '{{ ansible_hostname }}'
              pg_port:   '5432'
              cluster:   'main'
    metric_relabel_configs:
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_[^nps].*'
     #    action: drop
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_.*t?'
     #    action: drop

        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop

  - job_name: postgres4
    honor_labels: true
    static_configs:
        - targets: ['{{ ansible_hostname }}:9188'] 
          labels:
              host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
              hostname:  '{{ ansible_hostname }}'
              pg_port:   '5433'
              cluster:   'karat'
    metric_relabel_configs:
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_[^nps].*'
     #    action: drop
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_.*t?'
     #    action: drop

        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop


  - job_name: node
    scrape_interval:  10s
    static_configs:
      - targets: ['localhost:9100']
        labels:
             host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
             hostname:  '{{ ansible_hostname }}'

  - job_name:       'federate'
    scrape_interval: 15s
    honor_labels:   true
    metrics_path:   '/federate'
    params:
       'match[]':
               - '{job="prometheus"}'
               - '{job="node"}'
               - '{job=~"postgres.*"}'
               - '{job="grok"}'
                 #- '{job="node"}'
                 #- '{__name__=~"job:.*"}'

    static_configs:
        - targets:    ['<client-servername>:9090']    #TODO: MUST changeme
