global:
  scrape_interval:      {{ scrape_interval     | default( '1m'  )  }}
  scrape_timeout:       {{ scrape_timeout      | default( '10s' )  }} 
  evaluation_interval:  {{ evaluation_interval | default( '1m'  )  }}
  # sample_limit:       {{ sample_limit        | default( '10000' )  }}

  # Labels when communicating with  external systems (federation, remote storage, Alertmanager).
  external_labels:
      server_ip: '{{ ansible_all_ipv4_addresses.0 }}'
      hostname : '{{ ansible_hostname }}'

#alerting:
   #alertmanagers:
   #- static_configs:
   # - targets: ['localhost:9093']

rule_files:
   - "rules/memory.yml"
  # - "second_rules.yml"

scrape_configs:

  - job_name: node
    static_configs:
      - targets: ['qft:9100']
        labels:
             server_ip: '{{ ansible_all_ipv4_addresses.0 }}'
             hostname : '{{ ansible_hostname }}'


