####################################################   systemd
- name:        install systemd file
  copy:        src=etc/systemd/system/pgspray.service     dest="/etc/systemd/system/"     owner=root

- name:        install systemd file  
  copy:        src=etc/systemd/system/pgspray_psgi.service     dest="/etc/systemd/system/"     owner=root

####################################################   reload servers
- name:       reload  daemon
  systemd:    daemon_reload="yes"

- wait_for:    delay=3 timeout=0

- name:       reload  pgspray
  no_log:     true
  systemd:    name="pgspray"   daemon_reload="yes"  state=stopped  enabled=no
  when:       ansible_facts.services["pgspray.service"].state  == 'disabled'

- name:       reload  pgspray_psgi
  no_log:     true
  systemd:    name="pgspray_psgi"   daemon_reload="yes"  state=stopped  enabled=no
  when:       ansible_facts.services["pgspray_psgi.service"].state  == 'disabled'

- name:       reload  pgspray
  no_log:     true
  systemd:    name="pgspray"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["pgspray.service"].state  == 'running'

- name:       reload  pgspray_psgi
  no_log:     true
  systemd:    name="pgspray_psgi"   daemon_reload="yes"  state=restarted  enabled=no
  when:       ansible_facts.services["pgspray_psgi.service"].state  == 'running'
  #
