groups:
  - name: MemFree
    #interval: <duration> | default = global.evaluation_interval ]
    interval: 10s
    rules:
       - record: node_memory_ioannis_MemFree
         expr:   node_memory_total_bytes - node_memory_wired_bytes  - node_memory_active_bytes - node_memory_compressed_bytes 

  - name: MemUsed
    #interval: <duration> | default = global.evaluation_interval ]
    interval: 10s
    rules:
       - record: node_memory_ioannis_MemUsed
         expr:   node_memory_wired_bytes  + node_memory_active_bytes + node_memory_compressed_bytes 

  - name: MemBufCach
    #interval: <duration> | default = global.evaluation_interval ]
    interval: 10s
    rules:
       - record: node_memory_ioannis_MemBufCash
         expr:   0

  - name: MemTotal
    interval: 10s
    rules:
       - record: node_memory_ioannis_MemTotal
         expr:   node_memory_total_bytes
