.PHONY:         $(shell ls)
.SILENT:
.DEFAULT_GOAL = apache2

SUDO = sudo

all: 

#########################################################################################
apache2 apa:

	#rsync -arv  $(foreach i,$(ioannis_files),~ioannis/$i)     $@/
	#ansible-vault-3.6 encrypt                                 $@/.gnupg.tar
