- name:        Files   /etc/consul.d/*
  synchronize:  src="etc/consul.d/"  dest="/etc/consul.d"    delete='no'  owner=no  dirs=yes rsync_opts=--ignore-existing

- name:    copy token (becaue it is ansible-valuted) 
  copy:    src="etc/consul.d/consul.token"  dest="/etc/consul.d"    owner=root  mode=640

####################################################  /etc/prometheus  TEMPLATES
#
- name:        Templates /etc/consul.d/*
  template:    src=etc/consul/{{ item }}      dest="/etc/consul.d/"     owner=root
  with_items:
      -  basic.json  
      -  pgbouncer_exporter.json-  
      -  postgres_exporter_5432.json
      -  grok_exporter_main.json  
      -  grok_exporter_karat.json-  
      #-  grok_exporter_green.json-  
      -  node_exporter.json  
      -  postgres_exporter_5433.json-

####################################################  symlinks 
- name:    data directory 
  when:    os_family  == 'Darwin'  
  file:    path="/var/lib/consul"    state=directory   owner=ioannis   force=yes
####################################################  /etc/default
- name:        /etc/default/consul
  copy:       src=etc/default/consul    dest=/etc/default/consul    owner=root   
####################################################   reload servers
