#https://github.com/prometheus/prometheus/blob/master/config/testdata/conf.good.yml#L32-L39
 
- targets:
         - 127.0.0.1:2020  # fluent-bit
         - 127.0.0.1:3100  # loki
         - 127.0.0.1:5000  # plack
         - 127.0.0.1:5432  # main
         - 127.0.0.1:5433  # karat
         - 127.0.0.1:6543  # pgbouncer
         - 127.0.0.1:8500  # consul http
         - 127.0.0.1:9080  # promtail
         - 127.0.0.1:9091  # pushgateway
         - 127.0.0.1:9100  # node
         - 127.0.0.1:9115  # blackbox
         - 127.0.0.1:9144  # grok
         - 127.0.0.1:9145  # grok karat  
         - 127.0.0.1:9187  # postgres main  exporter
         - 127.0.0.1:9188  # postgres karat exporter
  labels:
      job:       blackbox
      hostname:  '{{ ansible_hostname }}'
      host_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
