#Conuration documentation: https://prometheus.io/docs/operating/configuration
 
global:
  scrape_interval:      {{ scrape_interval     | default( '1m'  )  }}
  scrape_timeout:       {{ scrape_timeout      | default( '10s' )  }} 
  evaluation_interval:  {{ evaluation_interval | default( '1m'  )  }}
  # sample_limit:       {{ sample_limit        | default( '10000' )  }}

  # Labels when communicating with  external systems (federation, remote storage, Alertmanager).
  external_labels:
      server_ip: '{{ ansible_all_ipv4_addresses.0 }}'
      hostname : '{{ ansible_hostname }}'

rule_files:
   - "rules/memory.yml"
    #- "/etc/prometheus/first_alert.yml"
 
scrape_configs:

  - job_name: 'postgres_5434'
    honor_labels: true
    static_configs:
        - targets: ['localhost:9487'] 
          labels:
              server : 'localhost:5434'
              pg_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
              pg_host : '{{ ansible_hostname }}'
              pg_port : '5434'
    metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop

  - job_name: 'pgbounce'
    honor_labels: true
    static_configs:
        - targets: ['localhost:9911'] 

  - job_name: 'postgres'
    honor_labels: true
    static_configs:
        - targets: ['localhost:9187'] 
          labels:
              server : 'localhost:5432'
              pg_ip:   '{{ ansible_all_ipv4_addresses.0 }}'
              pg_host : '{{ ansible_hostname }}'
              pg_port : '5434'
    metric_relabel_configs:
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_[^nps].*'
     #    action: drop
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_.*t?'
     #    action: drop

        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop



  - job_name: node
    scrape_interval:  10s
    static_configs:
      - targets: ['localhost:9100']
        labels:
             server_ip: '{{ ansible_all_ipv4_addresses.0 }}'
             hostname : '{{ ansible_hostname }}'


#remote_write:
#       - url: http://localhost:9201/write
