#Conuration documentation: https://prometheus.io/docs/operating/configuration
 
global:
  scrape_interval:      1m      # Default is every 1 minute.
  scrape_timeout:       1m      # Default 10s
  evaluation_interval:  4m      # Default is every 1 minute.      Evaluates rules 
  # sample_limit:       5000      # upper limit num of ts we can scrape


rule_files:
    # - "/etc/prometheus/first_rules.yml"
     - "/etc/prometheus/first_alert.yml"
 
scrape_configs:

  - job_name: 'postgres_5434'
    honor_labels: true
    static_configs:
        - targets: ['localhost:9487'] 
          labels:
              server : 'localhost:5434'
    metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop

  - job_name: 'pgbounce'
    honor_labels: true
    static_configs:
        - targets: ['localhost:9911'] 

  - job_name: 'postgres'
    honor_labels: true
    static_configs:
        - targets: ['localhost:9187'] 
          labels:
              server : 'localhost:5432'
    metric_relabel_configs:
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_[^nps].*'
     #    action: drop
     #  - source_labels: [__name__]
     #    regex: 'pg_settings_.*t?'
     #    action: drop

        - source_labels: [__name__]
          regex: 'pg_settings_s[ysqtu].*'
          action: drop
        - source_labels: [datname]
          regex: '^template[012]'
          action: drop



  - job_name: node
    scrape_interval:  10s
    static_configs:
      - targets: ['localhost:9100']
        labels:
             server_ip: '{{ ansible_all_ipv4_addresses.0 }}'
             hostname : '{{ ansible_hostname }}'



#remote_write:
#       - url: http://localhost:9201/write
